'use strict';

// Top 100 most used Danish verbs
// group: 'ede' | 'te' | 'irregular'
const VERBS = [
  { id: 1,  inf: 'at være',     meaning: 'be',                        present: 'er',         past: 'var',        perfect: 'har været',     imp: 'vær',      group: 'irregular' },
  { id: 2,  inf: 'at have',     meaning: 'have',                      present: 'har',        past: 'havde',      perfect: 'har haft',      imp: 'hav',      group: 'irregular' },
  { id: 3,  inf: 'at kunne',    meaning: 'can / be able to',          present: 'kan',        past: 'kunne',      perfect: 'har kunnet',    imp: '—',        group: 'irregular' },
  { id: 4,  inf: 'at blive',    meaning: 'become / remain',           present: 'bliver',     past: 'blev',       perfect: 'er blevet',     imp: 'bliv',     group: 'irregular' },
  { id: 5,  inf: 'at skulle',   meaning: 'must / be supposed to',     present: 'skal',       past: 'skulle',     perfect: 'har skullet',   imp: '—',        group: 'irregular' },
  { id: 6,  inf: 'at ville',    meaning: 'want to / will',            present: 'vil',        past: 'ville',      perfect: 'har villet',    imp: '—',        group: 'irregular' },
  { id: 7,  inf: 'at få',       meaning: 'get / receive',             present: 'får',        past: 'fik',        perfect: 'har fået',      imp: 'få',       group: 'irregular' },
  { id: 8,  inf: 'at sige',     meaning: 'say',                       present: 'siger',      past: 'sagde',      perfect: 'har sagt',      imp: 'sig',      group: 'irregular' },
  { id: 9,  inf: 'at komme',    meaning: 'come',                      present: 'kommer',     past: 'kom',        perfect: 'er kommet',     imp: 'kom',      group: 'irregular' },
  { id: 10, inf: 'at gå',       meaning: 'go / walk',                 present: 'går',        past: 'gik',        perfect: 'er gået',       imp: 'gå',       group: 'irregular' },
  { id: 11, inf: 'at gøre',     meaning: 'do / make',                 present: 'gør',        past: 'gjorde',     perfect: 'har gjort',     imp: 'gør',      group: 'irregular' },
  { id: 12, inf: 'at se',       meaning: 'see',                       present: 'ser',        past: 'så',         perfect: 'har set',       imp: 'se',       group: 'irregular' },
  { id: 13, inf: 'at måtte',    meaning: 'may / must',                present: 'må',         past: 'måtte',      perfect: 'har måttet',    imp: '—',        group: 'irregular' },
  { id: 14, inf: 'at tage',     meaning: 'take',                      present: 'tager',      past: 'tog',        perfect: 'har taget',     imp: 'tag',      group: 'irregular' },
  { id: 15, inf: 'at give',     meaning: 'give',                      present: 'giver',      past: 'gav',        perfect: 'har givet',     imp: 'giv',      group: 'irregular' },
  { id: 16, inf: 'at stå',      meaning: 'stand',                     present: 'står',       past: 'stod',       perfect: 'har stået',     imp: 'stå',      group: 'irregular' },
  { id: 17, inf: 'at finde',    meaning: 'find',                      present: 'finder',     past: 'fandt',      perfect: 'har fundet',    imp: 'find',     group: 'irregular' },
  { id: 18, inf: 'at holde',    meaning: 'hold / keep',               present: 'holder',     past: 'holdt',      perfect: 'har holdt',     imp: 'hold',     group: 'irregular' },
  { id: 19, inf: 'at sætte',    meaning: 'put / set',                 present: 'sætter',     past: 'satte',      perfect: 'har sat',       imp: 'sæt',      group: 'irregular' },
  { id: 20, inf: 'at vise',     meaning: 'show',                      present: 'viser',      past: 'viste',      perfect: 'har vist',      imp: 'vis',      group: 'te' },
  { id: 21, inf: 'at bruge',    meaning: 'use',                       present: 'bruger',     past: 'brugte',     perfect: 'har brugt',     imp: 'brug',     group: 'te' },
  { id: 22, inf: 'at ligge',    meaning: 'lie / be located',          present: 'ligger',     past: 'lå',         perfect: 'har ligget',    imp: 'lig',      group: 'irregular' },
  { id: 23, inf: 'at vide',     meaning: 'know (a fact)',             present: 'ved',        past: 'vidste',     perfect: 'har vidst',     imp: 'vid',      group: 'irregular' },
  { id: 24, inf: 'at tro',      meaning: 'believe / think',          present: 'tror',       past: 'troede',     perfect: 'har troet',     imp: 'tro',      group: 'ede' },
  { id: 25, inf: 'at mene',     meaning: 'mean / think',             present: 'mener',      past: 'mente',      perfect: 'har ment',      imp: 'men',      group: 'te' },
  { id: 26, inf: 'at ske',      meaning: 'happen',                    present: 'sker',       past: 'skete',      perfect: 'er sket',       imp: '—',        group: 'te' },
  { id: 27, inf: 'at fortælle', meaning: 'tell',                      present: 'fortæller',  past: 'fortalte',   perfect: 'har fortalt',   imp: 'fortæl',   group: 'irregular' },
  { id: 28, inf: 'at høre',     meaning: 'hear',                      present: 'hører',      past: 'hørte',      perfect: 'har hørt',      imp: 'hør',      group: 'te' },
  { id: 29, inf: 'at lave',     meaning: 'make / do',                 present: 'laver',      past: 'lavede',     perfect: 'har lavet',     imp: 'lav',      group: 'ede' },
  { id: 30, inf: 'at lægge',    meaning: 'lay / put',                 present: 'lægger',     past: 'lagde',      perfect: 'har lagt',      imp: 'læg',      group: 'irregular' },
  { id: 31, inf: 'at skrive',   meaning: 'write',                     present: 'skriver',    past: 'skrev',      perfect: 'har skrevet',   imp: 'skriv',    group: 'irregular' },
  { id: 32, inf: 'at sidde',    meaning: 'sit',                       present: 'sidder',     past: 'sad',        perfect: 'har siddet',    imp: 'sid',      group: 'irregular' },
  { id: 33, inf: 'at lade',     meaning: 'let / allow',               present: 'lader',      past: 'lod',        perfect: 'har ladet',     imp: 'lad',      group: 'irregular' },
  { id: 34, inf: 'at synes',    meaning: 'think / find / seem',       present: 'synes',      past: 'syntes',     perfect: 'har syntes',    imp: '—',        group: 'irregular' },
  { id: 35, inf: 'at følge',    meaning: 'follow',                    present: 'følger',     past: 'fulgte',     perfect: 'har fulgt',     imp: 'følg',     group: 'te' },
  { id: 36, inf: 'at begynde',  meaning: 'begin',                     present: 'begynder',   past: 'begyndte',   perfect: 'er begyndt',    imp: 'begynd',   group: 'te' },
  { id: 37, inf: 'at køre',     meaning: 'drive / travel',            present: 'kører',      past: 'kørte',      perfect: 'har/er kørt',   imp: 'kør',      group: 'te' },
  { id: 38, inf: 'at stille',   meaning: 'put / place',               present: 'stiller',    past: 'stillede',   perfect: 'har stillet',   imp: 'stil',     group: 'ede' },
  { id: 39, inf: 'at tænke',    meaning: 'think',                     present: 'tænker',     past: 'tænkte',     perfect: 'har tænkt',     imp: 'tænk',     group: 'te' },
  { id: 40, inf: 'at kalde',    meaning: 'call / name',               present: 'kalder',     past: 'kaldte',     perfect: 'har kaldt',     imp: 'kald',     group: 'te' },
  { id: 41, inf: 'at ønske',    meaning: 'wish / want',               present: 'ønsker',     past: 'ønskede',    perfect: 'har ønsket',    imp: 'ønsk',     group: 'ede' },
  { id: 42, inf: 'at slå',      meaning: 'hit / beat',                present: 'slår',       past: 'slog',       perfect: 'har slået',     imp: 'slå',      group: 'irregular' },
  { id: 43, inf: 'at leve',     meaning: 'live',                      present: 'lever',      past: 'levede',     perfect: 'har levet',     imp: 'lev',      group: 'ede' },
  { id: 44, inf: 'at føre',     meaning: 'lead / carry',              present: 'fører',      past: 'førte',      perfect: 'har ført',      imp: 'før',      group: 'te' },
  { id: 45, inf: 'at burde',    meaning: 'ought to / should',         present: 'bør',        past: 'burde',      perfect: 'har burdet',    imp: '—',        group: 'irregular' },
  { id: 46, inf: 'at spørge',   meaning: 'ask',                       present: 'spørger',    past: 'spurgte',    perfect: 'har spurgt',    imp: 'spørg',    group: 'irregular' },
  { id: 47, inf: 'at arbejde',  meaning: 'work',                      present: 'arbejder',   past: 'arbejdede',  perfect: 'har arbejdet',  imp: 'arbejd',   group: 'ede' },
  { id: 48, inf: 'at skabe',    meaning: 'create',                    present: 'skaber',     past: 'skabte',     perfect: 'har skabt',     imp: 'skab',     group: 'te' },
  { id: 49, inf: 'at sende',    meaning: 'send',                      present: 'sender',     past: 'sendte',     perfect: 'har sendt',     imp: 'send',     group: 'te' },
  { id: 50, inf: 'at falde',    meaning: 'fall',                      present: 'falder',     past: 'faldt',      perfect: 'er faldet',     imp: 'fald',     group: 'irregular' },
  { id: 51, inf: 'at kende',    meaning: 'know / be familiar with',   present: 'kender',     past: 'kendte',     perfect: 'har kendt',     imp: 'kend',     group: 'te' },
  { id: 52, inf: 'at vælge',    meaning: 'choose',                    present: 'vælger',     past: 'valgte',     perfect: 'har valgt',     imp: 'vælg',     group: 'irregular' },
  { id: 53, inf: 'at tale',     meaning: 'speak',                     present: 'taler',      past: 'talte',      perfect: 'har talt',      imp: 'tal',      group: 'te' },
  { id: 54, inf: 'at læse',     meaning: 'read',                      present: 'læser',      past: 'læste',      perfect: 'har læst',      imp: 'læs',      group: 'te' },
  { id: 55, inf: 'at svare',    meaning: 'answer',                    present: 'svarer',     past: 'svarede',    perfect: 'har svaret',    imp: 'svar',     group: 'ede' },
  { id: 56, inf: 'at vende',    meaning: 'turn / return',             present: 'vender',     past: 'vendte',     perfect: 'har vendt',     imp: 'vend',     group: 'te' },
  { id: 57, inf: 'at vinde',    meaning: 'win',                       present: 'vinder',     past: 'vandt',      perfect: 'har vundet',    imp: 'vind',     group: 'irregular' },
  { id: 58, inf: 'at sælge',    meaning: 'sell',                      present: 'sælger',     past: 'solgte',     perfect: 'har solgt',     imp: 'sælg',     group: 'irregular' },
  { id: 59, inf: 'at hjælpe',   meaning: 'help',                      present: 'hjælper',    past: 'hjalp',      perfect: 'har hjulpet',   imp: 'hjælp',    group: 'irregular' },
  { id: 60, inf: 'at møde',     meaning: 'meet',                      present: 'møder',      past: 'mødte',      perfect: 'har mødt',      imp: 'mød',      group: 'te' },
  { id: 61, inf: 'at forsøge',  meaning: 'attempt / try',             present: 'forsøger',   past: 'forsøgte',   perfect: 'har forsøgt',   imp: 'forsøg',   group: 'te' },
  { id: 62, inf: 'at lære',     meaning: 'learn / teach',             present: 'lærer',      past: 'lærte',      perfect: 'har lært',      imp: 'lær',      group: 'te' },
  { id: 63, inf: 'at hedde',    meaning: 'be called',                 present: 'hedder',     past: 'hed',        perfect: 'har heddet',    imp: 'hed',      group: 'irregular' },
  { id: 64, inf: 'at betale',   meaning: 'pay',                       present: 'betaler',    past: 'betalte',    perfect: 'har betalt',    imp: 'betal',    group: 'te' },
  { id: 65, inf: 'at købe',     meaning: 'buy',                       present: 'køber',      past: 'købte',      perfect: 'har købt',      imp: 'køb',      group: 'te' },
  { id: 66, inf: 'at bo',       meaning: 'live / reside',             present: 'bor',        past: 'boede',      perfect: 'har boet',      imp: 'bo',       group: 'ede' },
  { id: 67, inf: 'at spise',    meaning: 'eat',                       present: 'spiser',     past: 'spiste',     perfect: 'har spist',     imp: 'spis',     group: 'te' },
  { id: 68, inf: 'at drikke',   meaning: 'drink',                     present: 'drikker',    past: 'drak',       perfect: 'har drukket',   imp: 'drik',     group: 'irregular' },
  { id: 69, inf: 'at sove',     meaning: 'sleep',                     present: 'sover',      past: 'sov',        perfect: 'har sovet',     imp: 'sov',      group: 'irregular' },
  { id: 70, inf: 'at løbe',     meaning: 'run',                       present: 'løber',      past: 'løb',        perfect: 'har løbet',     imp: 'løb',      group: 'irregular' },
  { id: 71, inf: 'at ringe',    meaning: 'call / ring',               present: 'ringer',     past: 'ringede',    perfect: 'har ringet',    imp: 'ring',     group: 'ede' },
  { id: 72, inf: 'at åbne',     meaning: 'open',                      present: 'åbner',      past: 'åbnede',     perfect: 'har åbnet',     imp: 'åbn',      group: 'ede' },
  { id: 73, inf: 'at lukke',    meaning: 'close',                     present: 'lukker',     past: 'lukkede',    perfect: 'har lukket',    imp: 'luk',      group: 'ede' },
  { id: 74, inf: 'at huske',    meaning: 'remember',                  present: 'husker',     past: 'huskede',    perfect: 'har husket',    imp: 'husk',     group: 'ede' },
  { id: 75, inf: 'at glemme',   meaning: 'forget',                    present: 'glemmer',    past: 'glemte',     perfect: 'har glemt',     imp: 'glem',     group: 'te' },
  { id: 76, inf: 'at vente',    meaning: 'wait',                      present: 'venter',     past: 'ventede',    perfect: 'har ventet',    imp: 'vent',     group: 'ede' },
  { id: 77, inf: 'at forstå',   meaning: 'understand',                present: 'forstår',    past: 'forstod',    perfect: 'har forstået',  imp: 'forstå',   group: 'irregular' },
  { id: 78, inf: 'at prøve',    meaning: 'try / test',                present: 'prøver',     past: 'prøvede',    perfect: 'har prøvet',    imp: 'prøv',     group: 'ede' },
  { id: 79, inf: 'at regne',    meaning: 'calculate / expect',        present: 'regner',     past: 'regnede',    perfect: 'har regnet',    imp: 'regn',     group: 'ede' },
  { id: 80, inf: 'at elske',    meaning: 'love',                      present: 'elsker',     past: 'elskede',    perfect: 'har elsket',    imp: 'elsk',     group: 'ede' },
  { id: 81, inf: 'at føle',     meaning: 'feel',                      present: 'føler',      past: 'følte',      perfect: 'har følt',      imp: 'føl',      group: 'te' },
  { id: 82, inf: 'at fortsætte',meaning: 'continue',                  present: 'fortsætter', past: 'fortsatte',  perfect: 'har fortsat',   imp: 'fortsæt',  group: 'irregular' },
  { id: 83, inf: 'at ændre',    meaning: 'change',                    present: 'ændrer',     past: 'ændrede',    perfect: 'har ændret',    imp: 'ændr',     group: 'ede' },
  { id: 84, inf: 'at bestemme', meaning: 'decide / determine',        present: 'bestemmer',  past: 'bestemte',   perfect: 'har bestemt',   imp: 'bestem',   group: 'te' },
  { id: 85, inf: 'at kræve',    meaning: 'require / demand',          present: 'kræver',     past: 'krævede',    perfect: 'har krævet',    imp: 'kræv',     group: 'ede' },
  { id: 86, inf: 'at udvikle',  meaning: 'develop',                   present: 'udvikler',   past: 'udviklede',  perfect: 'har udviklet',  imp: 'udvikl',   group: 'ede' },
  { id: 87, inf: 'at betyde',   meaning: 'mean / signify',            present: 'betyder',    past: 'betød',      perfect: 'har betydet',   imp: 'betyd',    group: 'irregular' },
  { id: 88, inf: 'at behøve',   meaning: 'need',                      present: 'behøver',    past: 'behøvede',   perfect: 'har behøvet',   imp: '—',        group: 'ede' },
  { id: 89, inf: 'at hente',    meaning: 'fetch / pick up',           present: 'henter',     past: 'hentede',    perfect: 'har hentet',    imp: 'hent',     group: 'ede' },
  { id: 90, inf: 'at bringe',   meaning: 'bring',                     present: 'bringer',    past: 'bragte',     perfect: 'har bragt',     imp: 'bring',    group: 'irregular' },
  { id: 91, inf: 'at rejse',    meaning: 'travel / leave',            present: 'rejser',     past: 'rejste',     perfect: 'har/er rejst',  imp: 'rejs',     group: 'te' },
  { id: 92, inf: 'at flytte',   meaning: 'move',                      present: 'flytter',    past: 'flyttede',   perfect: 'har/er flyttet',imp: 'flyt',     group: 'ede' },
  { id: 93, inf: 'at starte',   meaning: 'start',                     present: 'starter',    past: 'startede',   perfect: 'har startet',   imp: 'start',    group: 'ede' },
  { id: 94, inf: 'at passe',    meaning: 'fit / take care of',        present: 'passer',     past: 'passede',    perfect: 'har passet',    imp: 'pas',      group: 'ede' },
  { id: 95, inf: 'at handle',   meaning: 'act / shop / concern',      present: 'handler',    past: 'handlede',   perfect: 'har handlet',   imp: 'handl',    group: 'ede' },
  { id: 96, inf: 'at besøge',   meaning: 'visit',                     present: 'besøger',    past: 'besøgte',    perfect: 'har besøgt',    imp: 'besøg',    group: 'te' },
  { id: 97, inf: 'at forklare', meaning: 'explain',                   present: 'forklarer',  past: 'forklarede', perfect: 'har forklaret', imp: 'forklar',  group: 'ede' },
  { id: 98, inf: 'at træffe',   meaning: 'meet / make a decision',    present: 'træffer',    past: 'traf',       perfect: 'har truffet',   imp: 'træf',     group: 'irregular' },
  { id: 99, inf: 'at opleve',   meaning: 'experience',                present: 'oplever',    past: 'oplevede',   perfect: 'har oplevet',   imp: 'oplev',    group: 'ede' },
  { id: 100,inf: 'at virke',    meaning: 'work / seem',               present: 'virker',     past: 'virkede',    perfect: 'har virket',    imp: 'virk',     group: 'ede' },
  { id: 101, inf: 'at acceptere', meaning: 'accept', present: 'accepterer', past: 'accepterede', perfect: 'har accepteret', imp: 'accepter', group: 'ede' },
  { id: 102, inf: 'at adskille', meaning: 'separate', present: 'adskiller', past: 'adskilte', perfect: 'har adskilt', imp: 'adskill', group: 'te' },
  { id: 103, inf: 'at advare', meaning: 'warn', present: 'advarer', past: 'advarede', perfect: 'har advaret', imp: 'advar', group: 'ede' },
  { id: 104, inf: 'at afbryde', meaning: 'interrupt / stop', present: 'afbryder', past: 'afbrød', perfect: 'har afbrudt', imp: 'afbryd', group: 'irregular' },
  { id: 105, inf: 'at afgive', meaning: 'submit / deliver', present: 'afgiver', past: 'afgav', perfect: 'har afgivet', imp: 'afgiv', group: 'irregular' },
  { id: 106, inf: 'at afgøre', meaning: 'decide / determine', present: 'afgør', past: 'afgjorde', perfect: 'har afgjort', imp: 'afgør', group: 'irregular' },
  { id: 107, inf: 'at aflevere', meaning: 'hand in / deliver', present: 'afleverer', past: 'afleverede', perfect: 'har afleveret', imp: 'aflever', group: 'ede' },
  { id: 108, inf: 'at aflyse', meaning: 'cancel', present: 'aflyser', past: 'aflyste', perfect: 'har aflyst', imp: 'aflys', group: 'te' },
  { id: 109, inf: 'at afløse', meaning: 'replace / relieve', present: 'afløser', past: 'afløste', perfect: 'har afløst', imp: 'afløs', group: 'te' },
  { id: 110, inf: 'at afskaffe', meaning: 'abolish', present: 'afskaffer', past: 'afskaffede', perfect: 'har afskaffet', imp: 'afskaff', group: 'ede' },
  { id: 111, inf: 'at afslutte', meaning: 'finish / conclude', present: 'afslutter', past: 'afsluttede', perfect: 'har afsluttet', imp: 'afslutt', group: 'ede' },
  { id: 112, inf: 'at afvise', meaning: 'reject / refuse', present: 'afviser', past: 'afviste', perfect: 'har afvist', imp: 'afvis', group: 'te' },
  { id: 113, inf: 'at anbefale', meaning: 'recommend', present: 'anbefaler', past: 'anbefalede', perfect: 'har anbefalet', imp: 'anbefal', group: 'ede' },
  { id: 114, inf: 'at anbringe', meaning: 'place / position', present: 'anbringer', past: 'anbragte', perfect: 'har anbragt', imp: 'anbring', group: 'irregular' },
  { id: 115, inf: 'at ane', meaning: 'suspect / sense', present: 'aner', past: 'anede', perfect: 'har anet', imp: 'an', group: 'ede' },
  { id: 116, inf: 'at anerkende', meaning: 'recognize / acknowledge', present: 'anerkender', past: 'anerkendte', perfect: 'har anerkendt', imp: 'anerkend', group: 'te' },
  { id: 117, inf: 'at angive', meaning: 'state / specify', present: 'angiver', past: 'angav', perfect: 'har angivet', imp: 'angiv', group: 'irregular' },
  { id: 118, inf: 'at angå', meaning: 'concern / relate to', present: 'angår', past: 'angik', perfect: 'har angået', imp: 'angå', group: 'irregular' },
  { id: 119, inf: 'at anholde', meaning: 'arrest / detain', present: 'anholder', past: 'anholdt', perfect: 'har anholdt', imp: 'anhold', group: 'irregular' },
  { id: 120, inf: 'at ankomme', meaning: 'arrive', present: 'ankommer', past: 'ankom', perfect: 'er ankommet', imp: 'ankomm', group: 'irregular' },
  { id: 121, inf: 'at anmelde', meaning: 'report / review', present: 'anmelder', past: 'anmeldte', perfect: 'har anmeldt', imp: 'anmeld', group: 'te' },
  { id: 122, inf: 'at anse', meaning: 'consider / regard', present: 'anser', past: 'anså', perfect: 'har anset', imp: 'ans', group: 'irregular' },
  { id: 123, inf: 'at ansætte', meaning: 'hire / employ', present: 'ansætter', past: 'ansatte', perfect: 'har ansat', imp: 'ansætt', group: 'irregular' },
  { id: 124, inf: 'at anvende', meaning: 'use / apply', present: 'anvender', past: 'anvendte', perfect: 'har anvendt', imp: 'anvend', group: 'te' },
  { id: 125, inf: 'at arrangere', meaning: 'arrange / organize', present: 'arrangerer', past: 'arrangerede', perfect: 'har arrangeret', imp: 'arranger', group: 'ede' },
  { id: 126, inf: 'at arrestere', meaning: 'arrest', present: 'arresterer', past: 'arresterede', perfect: 'har arresteret', imp: 'arrester', group: 'ede' },
  { id: 127, inf: 'at bage', meaning: 'bake', present: 'bager', past: 'bagte', perfect: 'har bagt', imp: 'bag', group: 'te' },
  { id: 128, inf: 'at banke', meaning: 'knock / bang', present: 'banker', past: 'bankede', perfect: 'har banket', imp: 'bank', group: 'ede' },
  { id: 129, inf: 'at bede', meaning: 'ask / pray', present: 'beder', past: 'bad', perfect: 'har bedt', imp: 'bed', group: 'irregular' },
  { id: 130, inf: 'at befinde', meaning: 'be located / be', present: 'befinder', past: 'befandt', perfect: 'har befundet', imp: 'befind', group: 'irregular' },
  { id: 131, inf: 'at begrave', meaning: 'bury', present: 'begraver', past: 'begravede', perfect: 'har begravet', imp: 'begrav', group: 'ede' },
  { id: 132, inf: 'at begrænse', meaning: 'limit / restrict', present: 'begrænser', past: 'begrænsede', perfect: 'har begrænset', imp: 'begræns', group: 'ede' },
  { id: 133, inf: 'at begå', meaning: 'commit', present: 'begår', past: 'begik', perfect: 'har begået', imp: 'begå', group: 'irregular' },
  { id: 134, inf: 'at behandle', meaning: 'treat / handle', present: 'behandler', past: 'behandlede', perfect: 'har behandlet', imp: 'behandl', group: 'ede' },
  { id: 135, inf: 'at beholde', meaning: 'keep / retain', present: 'beholder', past: 'beholdt', perfect: 'har beholdt', imp: 'behold', group: 'irregular' },
  { id: 136, inf: 'at beklage', meaning: 'regret / complain', present: 'beklager', past: 'beklagede', perfect: 'har beklaget', imp: 'beklag', group: 'ede' },
  { id: 137, inf: 'at bekræfte', meaning: 'confirm', present: 'bekræfter', past: 'bekræftede', perfect: 'har bekræfted', imp: 'bekræft', group: 'ede' },
  { id: 138, inf: 'at bemærke', meaning: 'notice / remark', present: 'bemærker', past: 'bemærkede', perfect: 'har bemærket', imp: 'bemærk', group: 'ede' },
  { id: 139, inf: 'at benytte', meaning: 'use / make use of', present: 'benytter', past: 'benyttede', perfect: 'har benyttet', imp: 'benytt', group: 'ede' },
  { id: 140, inf: 'at beskrive', meaning: 'describe', present: 'beskriver', past: 'beskrev', perfect: 'har beskrevet', imp: 'beskriv', group: 'irregular' },
  { id: 141, inf: 'at beskytte', meaning: 'protect', present: 'beskytter', past: 'beskyttede', perfect: 'har beskyttet', imp: 'beskytt', group: 'ede' },
  { id: 142, inf: 'at beslutte', meaning: 'decide', present: 'beslutter', past: 'besluttede', perfect: 'har besluttet', imp: 'beslutt', group: 'ede' },
  { id: 143, inf: 'at bestille', meaning: 'order / book', present: 'bestiller', past: 'bestilte', perfect: 'har bestilt', imp: 'bestill', group: 'te' },
  { id: 144, inf: 'at bestå', meaning: 'consist / pass', present: 'består', past: 'bestod', perfect: 'har bestået', imp: 'bestå', group: 'irregular' },
  { id: 145, inf: 'at besætte', meaning: 'occupy', present: 'besætter', past: 'besatte', perfect: 'har besat', imp: 'besætt', group: 'irregular' },
  { id: 146, inf: 'at bevare', meaning: 'preserve / keep', present: 'bevarer', past: 'bevarede', perfect: 'har bevaret', imp: 'bevar', group: 'ede' },
  { id: 147, inf: 'at bevise', meaning: 'prove', present: 'beviser', past: 'beviste', perfect: 'har bevist', imp: 'bevis', group: 'te' },
  { id: 148, inf: 'at bevæge sig', meaning: 'move (oneself)', present: 'bevæger sig', past: 'bevægede sig', perfect: 'har bevæget sig', imp: 'bevæg sig', group: 'ede' },
  { id: 149, inf: 'at bide', meaning: 'bite', present: 'bider', past: 'bed', perfect: 'har bidt', imp: 'bid', group: 'irregular' },
  { id: 150, inf: 'at bidrage', meaning: 'contribute', present: 'bidrager', past: 'bidrog', perfect: 'har bidraget', imp: 'bidrag', group: 'irregular' },
  { id: 151, inf: 'at binde', meaning: 'tie / bind', present: 'binder', past: 'bandt', perfect: 'har bundet', imp: 'bind', group: 'irregular' },
  { id: 152, inf: 'at blande', meaning: 'mix / blend', present: 'blander', past: 'blandede', perfect: 'har blandet', imp: 'bland', group: 'ede' },
  { id: 153, inf: 'at blæse', meaning: 'blow', present: 'blæser', past: 'blæste', perfect: 'har blæst', imp: 'blæs', group: 'te' },
  { id: 154, inf: 'at brede sig', meaning: 'spread (reflexive)', present: 'breder sig', past: 'bredte sig', perfect: 'har bredt sig', imp: 'bred sig', group: 'te' },
  { id: 155, inf: 'at bryde', meaning: 'break', present: 'bryder', past: 'brød', perfect: 'har brudt', imp: 'bryd', group: 'irregular' },
  { id: 156, inf: 'at bygge', meaning: 'build', present: 'bygger', past: 'byggede', perfect: 'har bygget', imp: 'bygg', group: 'ede' },
  { id: 157, inf: 'at bytte', meaning: 'swap / exchange', present: 'bytter', past: 'byttede', perfect: 'har byttet', imp: 'bytt', group: 'ede' },
  { id: 158, inf: 'at bære', meaning: 'carry / bear', present: 'bærer', past: 'bar', perfect: 'har båret', imp: 'bær', group: 'irregular' },
  { id: 159, inf: 'at citere', meaning: 'quote / cite', present: 'citerer', past: 'citerede', perfect: 'har citeret', imp: 'citer', group: 'ede' },
  { id: 160, inf: 'at danne', meaning: 'form / create', present: 'danner', past: 'dannede', perfect: 'har dannet', imp: 'dann', group: 'ede' },
  { id: 161, inf: 'at danse', meaning: 'dance', present: 'danser', past: 'dansede', perfect: 'har danset', imp: 'dans', group: 'ede' },
  { id: 162, inf: 'at dele', meaning: 'share / divide', present: 'deler', past: 'delte', perfect: 'har delt', imp: 'del', group: 'te' },
  { id: 163, inf: 'at deltage', meaning: 'participate', present: 'deltager', past: 'deltog', perfect: 'har deltaget', imp: 'deltag', group: 'irregular' },
  { id: 164, inf: 'at diskutere', meaning: 'discuss', present: 'diskuterer', past: 'diskuterede', perfect: 'har diskuteret', imp: 'diskuter', group: 'ede' },
  { id: 165, inf: 'at dominere', meaning: 'dominate', present: 'dominerer', past: 'dominerede', perfect: 'har domineret', imp: 'dominer', group: 'ede' },
  { id: 166, inf: 'at drage', meaning: 'go / depart', present: 'drager', past: 'drog', perfect: 'har draget', imp: 'drag', group: 'irregular' },
  { id: 167, inf: 'at dreje', meaning: 'turn / rotate', present: 'drejer', past: 'drejede', perfect: 'har drejet', imp: 'drej', group: 'ede' },
  { id: 168, inf: 'at drive', meaning: 'run / operate', present: 'driver', past: 'drev', perfect: 'har drevet', imp: 'driv', group: 'irregular' },
  { id: 169, inf: 'at dræbe', meaning: 'kill', present: 'dræber', past: 'dræbte', perfect: 'har dræbt', imp: 'dræb', group: 'te' },
  { id: 170, inf: 'at drøfte', meaning: 'discuss', present: 'drøfter', past: 'drøftede', perfect: 'har drøftet', imp: 'drøft', group: 'ede' },
  { id: 171, inf: 'at drømme', meaning: 'dream', present: 'drømmer', past: 'drømte', perfect: 'har drømt', imp: 'drømm', group: 'te' },
  { id: 172, inf: 'at dukke op', meaning: 'show up / appear', present: 'dukker op', past: 'dukkede op', perfect: 'er dukket op', imp: 'dukk op', group: 'ede' },
  { id: 173, inf: 'at dække', meaning: 'cover', present: 'dækker', past: 'dækkede', perfect: 'har dækket', imp: 'dækk', group: 'ede' },
  { id: 174, inf: 'at dø', meaning: 'die', present: 'dør', past: 'døde', perfect: 'er død', imp: 'dø', group: 'ede' },
  { id: 175, inf: 'at dømme', meaning: 'judge / sentence', present: 'dømmer', past: 'dømte', perfect: 'har dømt', imp: 'dømm', group: 'te' },
  { id: 176, inf: 'at efterlade', meaning: 'leave behind', present: 'efterlader', past: 'efterlod', perfect: 'har efterladt', imp: 'efterlad', group: 'irregular' },
  { id: 177, inf: 'at eje', meaning: 'own', present: 'ejer', past: 'ejede', perfect: 'har ejet', imp: 'ej', group: 'ede' },
  { id: 178, inf: 'at eksistere', meaning: 'exist', present: 'eksisterer', past: 'eksisterede', perfect: 'har eksisteret', imp: 'eksister', group: 'ede' },
  { id: 179, inf: 'at ende', meaning: 'end', present: 'ender', past: 'endte', perfect: 'er endt', imp: 'end', group: 'te' },
  { id: 180, inf: 'at erkende', meaning: 'realize / acknowledge', present: 'erkender', past: 'erkendte', perfect: 'har erkendt', imp: 'erkend', group: 'te' },
  { id: 181, inf: 'at erstatte', meaning: 'replace', present: 'erstatter', past: 'erstattede', perfect: 'har erstattet', imp: 'erstatt', group: 'ede' },
  { id: 182, inf: 'at fange', meaning: 'catch / capture', present: 'fanger', past: 'fangede', perfect: 'har fanget', imp: 'fang', group: 'ede' },
  { id: 183, inf: 'at fastholde', meaning: 'maintain / hold', present: 'fastholder', past: 'fastholdt', perfect: 'har fastholdt', imp: 'fasthold', group: 'irregular' },
  { id: 184, inf: 'at fastslå', meaning: 'establish / determine', present: 'fastslår', past: 'fastslog', perfect: 'har fastslået', imp: 'fastslå', group: 'irregular' },
  { id: 185, inf: 'at fastsætte', meaning: 'set / determine', present: 'fastsætter', past: 'fastsatte', perfect: 'har fastsat', imp: 'fastsætt', group: 'irregular' },
  { id: 186, inf: 'at fatte', meaning: 'grasp / understand', present: 'fatter', past: 'fattede', perfect: 'har fattet', imp: 'fatt', group: 'ede' },
  { id: 187, inf: 'at fejre', meaning: 'celebrate', present: 'fejrer', past: 'fejrede', perfect: 'har fejret', imp: 'fejr', group: 'ede' },
  { id: 188, inf: 'at fjerne', meaning: 'remove', present: 'fjerner', past: 'fjernede', perfect: 'har fjernet', imp: 'fjern', group: 'ede' },
  { id: 189, inf: 'at flygte', meaning: 'flee / escape', present: 'flygter', past: 'flygtede', perfect: 'er flygtet', imp: 'flygt', group: 'ede' },
  { id: 190, inf: 'at flyve', meaning: 'fly', present: 'flyver', past: 'fløj', perfect: 'har/er fløjet', imp: 'flyv', group: 'irregular' },
  { id: 191, inf: 'at fodre', meaning: 'feed', present: 'fodrer', past: 'fodrede', perfect: 'har fodret', imp: 'fodr', group: 'ede' },
  { id: 192, inf: 'at forbedre', meaning: 'improve', present: 'forbedrer', past: 'forbedrede', perfect: 'har forbedret', imp: 'forbedr', group: 'ede' },
  { id: 193, inf: 'at forberede', meaning: 'prepare', present: 'forbereder', past: 'forberedte', perfect: 'har forberedt', imp: 'forbered', group: 'te' },
  { id: 194, inf: 'at forbinde', meaning: 'connect / link', present: 'forbinder', past: 'forbandt', perfect: 'har forbundet', imp: 'forbind', group: 'irregular' },
  { id: 195, inf: 'at forblive', meaning: 'remain', present: 'forbliver', past: 'forblev', perfect: 'er forblevet', imp: 'forbliv', group: 'irregular' },
  { id: 196, inf: 'at fordele', meaning: 'distribute', present: 'fordeler', past: 'fordelte', perfect: 'har fordelt', imp: 'fordel', group: 'te' },
  { id: 197, inf: 'at foregå', meaning: 'take place', present: 'foregår', past: 'foregik', perfect: 'er foregået', imp: 'foregå', group: 'irregular' },
  { id: 198, inf: 'at forekomme', meaning: 'occur / happen', present: 'forekommer', past: 'forekom', perfect: 'er forekommet', imp: 'forekomm', group: 'irregular' },
  { id: 199, inf: 'at forelske sig', meaning: 'fall in love', present: 'forelsker sig', past: 'forelskede sig', perfect: 'har forelsket sig', imp: 'forelsk sig', group: 'ede' },
  { id: 200, inf: 'at forene', meaning: 'unite / combine', present: 'forener', past: 'forenede', perfect: 'har forenet', imp: 'foren', group: 'ede' },
  { id: 201, inf: 'at foreslå', meaning: 'suggest', present: 'foreslår', past: 'foreslog', perfect: 'har foreslået', imp: 'foreslå', group: 'irregular' },
  { id: 202, inf: 'at forestille sig', meaning: 'imagine', present: 'forestiller sig', past: 'forestillede sig', perfect: 'har forestillet sig', imp: 'forestill sig', group: 'ede' },
  { id: 203, inf: 'at foretage sig', meaning: 'do / undertake', present: 'foretager sig', past: 'foretog sig', perfect: 'har foretaget sig', imp: 'foretag sig', group: 'irregular' },
  { id: 204, inf: 'at foretrække', meaning: 'prefer', present: 'foretrækker', past: 'foretrak', perfect: 'har foretrukket', imp: 'foretrækk', group: 'irregular' },
  { id: 205, inf: 'at forhandle', meaning: 'negotiate', present: 'forhandler', past: 'forhandlede', perfect: 'har forhandlet', imp: 'forhandl', group: 'ede' },
  { id: 206, inf: 'at forhindre', meaning: 'prevent', present: 'forhindrer', past: 'forhindrede', perfect: 'har forhindret', imp: 'forhindr', group: 'ede' },
  { id: 207, inf: 'at forholde sig', meaning: 'relate to / deal with', present: 'forholder sig', past: 'forholdt sig', perfect: 'har forholdt sig', imp: 'forhold sig', group: 'irregular' },
  { id: 208, inf: 'at forlade', meaning: 'leave', present: 'forlader', past: 'forlod', perfect: 'har forladt', imp: 'forlad', group: 'irregular' },
  { id: 209, inf: 'at forlange', meaning: 'demand', present: 'forlanger', past: 'forlangte', perfect: 'har forlangt', imp: 'forlang', group: 'te' },
  { id: 210, inf: 'at formulere', meaning: 'formulate', present: 'formulerer', past: 'formulerede', perfect: 'har formuleret', imp: 'formuler', group: 'ede' },
  { id: 211, inf: 'at formå', meaning: 'manage to', present: 'formår', past: 'formåede', perfect: 'har fomået', imp: 'formå', group: 'ede' },
  { id: 212, inf: 'at forsinke', meaning: 'delay', present: 'forsinker', past: 'forsinkede', perfect: 'har forsinket', imp: 'forsink', group: 'ede' },
  { id: 213, inf: 'at forsvare', meaning: 'defend', present: 'forsvarer', past: 'forsvarede', perfect: 'har forsvaret', imp: 'forsvar', group: 'ede' },
  { id: 214, inf: 'at forsvinde', meaning: 'disappear / vanish', present: 'forsvinder', past: 'forsvandt', perfect: 'er forsvundet', imp: 'forsvind', group: 'irregular' },
  { id: 215, inf: 'at fortjene', meaning: 'deserve / earn', present: 'fortjener', past: 'fortjente', perfect: 'har fortjent', imp: 'fortjen', group: 'te' },
  { id: 216, inf: 'at forudsætte', meaning: 'presuppose / assume', present: 'forudsætter', past: 'forudsatte', perfect: 'har/erforudsat', imp: 'forudsætt', group: 'irregular' },
  { id: 217, inf: 'at forvandle', meaning: 'transform', present: 'forvandler', past: 'forvandlede', perfect: 'har forvandlet', imp: 'forvandl', group: 'ede' },
  { id: 218, inf: 'at forvente', meaning: 'expect', present: 'forventer', past: 'forventede', perfect: 'har forventet', imp: 'forvent', group: 'ede' },
  { id: 219, inf: 'at fremgå', meaning: 'appear / be evident', present: 'fremgår', past: 'fremgik', perfect: 'er fremgået', imp: 'fremgå', group: 'irregular' },
  { id: 220, inf: 'at fremhæve', meaning: 'emphasize / highlight', present: 'fremhæver', past: 'fremhævede', perfect: 'har fremhævet', imp: 'fremhæv', group: 'ede' },
  { id: 221, inf: 'at fremlægge', meaning: 'present / lay out', present: 'fremlægger', past: 'fremlagde', perfect: 'har fremlagt', imp: 'fremlægg', group: 'irregular' },
  { id: 222, inf: 'at fremstille', meaning: 'produce / portray', present: 'fremstiller', past: 'fremstillede', perfect: 'har fremstillet', imp: 'fremstill', group: 'ede' },
  { id: 223, inf: 'at fremsætte', meaning: 'propose / present', present: 'fremsætter', past: 'fremsatte', perfect: 'har fremsat', imp: 'fremsætt', group: 'irregular' },
  { id: 224, inf: 'at friste', meaning: 'tempt', present: 'frister', past: 'fristede', perfect: 'har fristet', imp: 'frist', group: 'ede' },
  { id: 225, inf: 'at frygte', meaning: 'fear', present: 'frygter', past: 'frygtede', perfect: 'har frygtet', imp: 'frygt', group: 'ede' },
  { id: 226, inf: 'at fungere', meaning: 'function / work', present: 'fungerer', past: 'fungerede', perfect: 'har fungeret', imp: 'funger', group: 'ede' },
  { id: 227, inf: 'at fylde', meaning: 'fill', present: 'fylder', past: 'fyldte', perfect: 'har fyldt', imp: 'fyld', group: 'te' },
  { id: 228, inf: 'at fyre', meaning: 'fire / sack', present: 'fyrer', past: 'fyrede', perfect: 'har fyret', imp: 'fyr', group: 'ede' },
  { id: 229, inf: 'at føde', meaning: 'give birth', present: 'føder', past: 'fødte', perfect: 'har født', imp: 'fød', group: 'te' },
  { id: 230, inf: 'at gemme', meaning: 'save / hide', present: 'gemmer', past: 'gemte', perfect: 'har gemt', imp: 'gemm', group: 'te' },
  { id: 231, inf: 'at genere', meaning: 'bother / annoy', present: 'generer', past: 'generede', perfect: 'har generet', imp: 'gener', group: 'ede' },
  { id: 232, inf: 'at gennemføre', meaning: 'carry out / complete', present: 'gennemfører', past: 'gennemførte', perfect: 'har gennemført', imp: 'gennemfør', group: 'te' },
  { id: 233, inf: 'at gennemgå', meaning: 'review / go through', present: 'gennemgår', past: 'gennemgik', perfect: 'har gennemgået', imp: 'gennemgå', group: 'irregular' },
  { id: 234, inf: 'at gentage', meaning: 'repeat', present: 'gentager', past: 'gentog', perfect: 'har gentaget', imp: 'gentag', group: 'irregular' },
  { id: 235, inf: 'at gide', meaning: 'feel like / bother', present: 'gider', past: 'gad', perfect: 'har gidet', imp: 'gid', group: 'irregular' },
  { id: 236, inf: 'at gifte sig', meaning: 'get married', present: 'gifter sig', past: 'giftede sig', perfect: 'har giftet sig', imp: 'gift sig', group: 'ede' },
  { id: 237, inf: 'at glide', meaning: 'slide / glide', present: 'glider', past: 'gled', perfect: 'er gledet', imp: 'glid', group: 'irregular' },
  { id: 238, inf: 'at glæde sig', meaning: 'look forward / rejoice', present: 'glæder sig', past: 'glædede sig', perfect: 'har glædet sig', imp: 'glæd sig', group: 'ede' },
  { id: 239, inf: 'at godkende', meaning: 'approve', present: 'godkender', past: 'godkendte', perfect: 'har godkendt', imp: 'godkend', group: 'te' },
  { id: 240, inf: 'at gribe', meaning: 'grab / seize', present: 'griber', past: 'greb', perfect: 'har grebet', imp: 'grib', group: 'irregular' },
  { id: 241, inf: 'at grine', meaning: 'laugh', present: 'griner', past: 'grinede', perfect: 'har grinet', imp: 'grin', group: 'ede' },
  { id: 242, inf: 'at græde', meaning: 'cry', present: 'græder', past: 'græd', perfect: 'har grædt', imp: 'græd', group: 'irregular' },
  { id: 243, inf: 'at hade', meaning: 'hate', present: 'hader', past: 'hadede', perfect: 'har hadet', imp: 'had', group: 'ede' },
  { id: 244, inf: 'at henvende sig', meaning: 'address / turn to', present: 'henvender sig', past: 'henvendte sig', perfect: 'har henvendt sig', imp: 'henvend sig', group: 'te' },
  { id: 245, inf: 'at henvise', meaning: 'refer', present: 'henviser', past: 'henviste', perfect: 'har henvist', imp: 'henvis', group: 'te' },
  { id: 246, inf: 'at herske', meaning: 'rule / prevail', present: 'hersker', past: 'herskede', perfect: 'har hersket', imp: 'hersk', group: 'ede' },
  { id: 247, inf: 'at hilse', meaning: 'greet / say hello', present: 'hilser', past: 'hilste', perfect: 'har hilst', imp: 'hils', group: 'te' },
  { id: 248, inf: 'at hindre', meaning: 'hinder / prevent', present: 'hindrer', past: 'hindrede', perfect: 'har hindret', imp: 'hindr', group: 'ede' },
  { id: 249, inf: 'at hoppe', meaning: 'jump', present: 'hopper', past: 'hoppede', perfect: 'har/er hoppet', imp: 'hopp', group: 'ede' },
  { id: 250, inf: 'at hvile sig', meaning: 'rest / relax', present: 'hviler sig', past: 'hvilede sig', perfect: 'har hvilet sig', imp: 'hvil sig', group: 'ede' },
  { id: 251, inf: 'at hviske', meaning: 'whisper', present: 'hvisker', past: 'hviskede', perfect: 'har hvisket', imp: 'hvisk', group: 'ede' },
  { id: 252, inf: 'at hælde', meaning: 'pour / tilt', present: 'hælder', past: 'hældte', perfect: 'har hældt', imp: 'hæld', group: 'te' },
  { id: 253, inf: 'at hænge (tr)', meaning: 'hang (something)', present: 'hænger', past: 'hængte', perfect: 'har hængt', imp: 'hæng', group: 'te' },
  { id: 254, inf: 'at hænge (intr)', meaning: 'be hanging / hang', present: 'hænger', past: 'hang', perfect: 'har hængt', imp: 'hæng', group: 'irregular' },
  { id: 255, inf: 'at hævde', meaning: 'claim / assert', present: 'hævder', past: 'Hævdede', perfect: 'har hævdet', imp: 'hævd', group: 'ede' },
  { id: 256, inf: 'at hæve', meaning: 'raise / lift', present: 'hæver', past: 'hævede', perfect: 'har hævet', imp: 'hæv', group: 'ede' },
  { id: 257, inf: 'at håbe', meaning: 'hope', present: 'håber', past: 'håbede', perfect: 'har håbet', imp: 'håb', group: 'ede' },
  { id: 258, inf: 'at inddrage', meaning: 'include / withdraw', present: 'inddrager', past: 'inddrog', perfect: 'har inddraget', imp: 'inddrag', group: 'irregular' },
  { id: 259, inf: 'at indebære', meaning: 'entail / involve', present: 'indebærer', past: 'indebar', perfect: 'har indebåret', imp: 'indebær', group: 'irregular' },
  { id: 260, inf: 'at indeholde', meaning: 'contain', present: 'indeholder', past: 'indeholdt', perfect: 'har indeholdt', imp: 'indehold', group: 'irregular' },
  { id: 261, inf: 'at indføre', meaning: 'introduce / implement', present: 'indfører', past: 'indførte', perfect: 'har indført', imp: 'indfør', group: 'te' },
  { id: 262, inf: 'at indgå', meaning: 'enter / be included', present: 'indgår', past: 'indgik', perfect: 'har indgået', imp: 'indgå', group: 'irregular' },
  { id: 263, inf: 'at indlede', meaning: 'begin / initiate', present: 'indleder', past: 'indledte', perfect: 'har indledt', imp: 'indled', group: 'te' },
  { id: 264, inf: 'at indrette', meaning: 'arrange / furnish', present: 'indretter', past: 'indrettede', perfect: 'har indrettet', imp: 'indrett', group: 'ede' },
  { id: 265, inf: 'at indrømme', meaning: 'admit', present: 'indrømmer', past: 'indrømmede', perfect: 'har indrømmet', imp: 'indrømm', group: 'ede' },
  { id: 266, inf: 'at indstille', meaning: 'adjust / set', present: 'indstiller', past: 'indstillede', perfect: 'har indstillet', imp: 'indstill', group: 'ede' },
  { id: 267, inf: 'at indtage', meaning: 'occupy / consume', present: 'indtager', past: 'indtog', perfect: 'har indtaget', imp: 'indtag', group: 'irregular' },
  { id: 268, inf: 'at installere', meaning: 'install', present: 'installerer', past: 'installerede', perfect: 'har installeret', imp: 'installer', group: 'ede' },
  { id: 269, inf: 'at inspirere', meaning: 'inspire', present: 'inspirerer', past: 'inspirerede', perfect: 'har inspireret', imp: 'inspirer', group: 'ede' },
  { id: 270, inf: 'at interessere', meaning: 'interest', present: 'interesserer', past: 'interesserede', perfect: 'har interesseret', imp: 'interesser', group: 'ede' },
  { id: 271, inf: 'at investere', meaning: 'invest', present: 'investerer', past: 'investerede', perfect: 'har investeret', imp: 'invester', group: 'ede' },
  { id: 272, inf: 'at invitere', meaning: 'invite', present: 'inviterer', past: 'inviterede', perfect: 'har inviteret', imp: 'inviter', group: 'ede' },
  { id: 273, inf: 'at irritere', meaning: 'annoy / irritate', present: 'irriterer', past: 'irriterede', perfect: 'har irriteret', imp: 'irriter', group: 'ede' },
  { id: 274, inf: 'at kaste', meaning: 'throw', present: 'kaster', past: 'kastede', perfect: 'har kastet', imp: 'kast', group: 'ede' },
  { id: 275, inf: 'at kigge', meaning: 'look', present: 'kigger', past: 'kiggede', perfect: 'har kigget', imp: 'kigg', group: 'ede' },
  { id: 276, inf: 'at klare', meaning: 'manage / cope', present: 'klarer', past: 'klarede', perfect: 'har klaret', imp: 'klar', group: 'ede' },
  { id: 277, inf: 'at klippe', meaning: 'cut', present: 'klipper', past: 'klippede', perfect: 'har klippet', imp: 'klipp', group: 'ede' },
  { id: 278, inf: 'at klæde', meaning: 'dress / suit', present: 'klæder', past: 'klædte', perfect: 'har klædt', imp: 'klæd', group: 'te' },
  { id: 279, inf: 'at knuse', meaning: 'crush / smash', present: 'knuser', past: 'knuste', perfect: 'har knust', imp: 'knus', group: 'te' },
  { id: 280, inf: 'at knytte', meaning: 'tie / attach', present: 'knytter', past: 'knyttede', perfect: 'har knyttet', imp: 'knytt', group: 'ede' },
  { id: 281, inf: 'at koge', meaning: 'boil / cook', present: 'koger', past: 'kogte', perfect: 'har kogt', imp: 'kog', group: 'te' },
  { id: 282, inf: 'at kombinere', meaning: 'combine', present: 'kombinerer', past: 'kombinerede', perfect: 'har kombineret', imp: 'kombiner', group: 'ede' },
  { id: 283, inf: 'at kommentere', meaning: 'comment', present: 'kommenterer', past: 'kommenterede', perfect: 'Har kommenteret', imp: 'kommenter', group: 'ede' },
  { id: 284, inf: 'at koncentrere sig', meaning: 'concentrate / focus', present: 'koncentrerer sig', past: 'koncentrede sig', perfect: 'har koncentreret sig', imp: 'koncentrer sig', group: 'ede' },
  { id: 285, inf: 'at konstatere', meaning: 'establish / note', present: 'konstaterer', past: 'konstaterede', perfect: 'har konstateret', imp: 'konstater', group: 'ede' },
  { id: 286, inf: 'at kontakte', meaning: 'contact', present: 'kontakter', past: 'kontaktede', perfect: 'har kontaktet', imp: 'kontakt', group: 'ede' },
  { id: 287, inf: 'at kontrollere', meaning: 'check / control', present: 'kontrollerer', past: 'kontrollerede', perfect: 'har kontrolleret', imp: 'kontroller', group: 'ede' },
  { id: 288, inf: 'at koste', meaning: 'cost', present: 'koster', past: 'kostede', perfect: 'har kostet', imp: 'kost', group: 'ede' },
  { id: 289, inf: 'at kritisere', meaning: 'criticize', present: 'kritiserer', past: 'kritiserede', perfect: 'har kritiseret', imp: 'kritiser', group: 'ede' },
  { id: 290, inf: 'at kunne lide', meaning: 'like / enjoy', present: 'kan lide', past: 'kunne lide', perfect: 'har kunnet lide', imp: 'kunn lide', group: 'irregular' },
  { id: 291, inf: 'at kysse', meaning: 'kiss', present: 'kysser', past: 'kyssede', perfect: 'har kysset', imp: 'kyss', group: 'ede' },
  { id: 292, inf: 'at kæmpe', meaning: 'fight / struggle', present: 'kæmper', past: 'kæmpede', perfect: 'har kæmpet', imp: 'kæmp', group: 'ede' },
  { id: 293, inf: 'at lade som om', meaning: 'pretend', present: 'lader som om', past: 'lod som om', perfect: 'har ladet som om', imp: 'lad som om', group: 'irregular' },
  { id: 294, inf: 'at lande', meaning: 'land', present: 'lander', past: 'landede', perfect: 'er landet', imp: 'land', group: 'ede' },
  { id: 295, inf: 'at le', meaning: 'laugh', present: 'ler', past: 'lo', perfect: 'har leet', imp: 'le', group: 'irregular' },
  { id: 296, inf: 'at lede', meaning: 'lead / search for', present: 'leder', past: 'ledte', perfect: 'har ledt', imp: 'led', group: 'te' },
  { id: 297, inf: 'at lege', meaning: 'play', present: 'leger', past: 'legede', perfect: 'har leget', imp: 'leg', group: 'ede' },
  { id: 298, inf: 'at leje', meaning: 'rent / hire', present: 'lejer', past: 'lejede', perfect: 'har lejet', imp: 'lej', group: 'ede' },
  { id: 299, inf: 'at lette', meaning: 'lighten / ease', present: 'letter', past: 'lettede', perfect: 'har/er lettet', imp: 'lett', group: 'ede' },
  { id: 300, inf: 'at levere', meaning: 'deliver', present: 'leverer', past: 'leverede', perfect: 'har leveret', imp: 'lever', group: 'ede' },
  { id: 301, inf: 'at lide', meaning: 'suffer', present: 'lider', past: 'led', perfect: 'har lidt', imp: 'lid', group: 'irregular' },
  { id: 302, inf: 'at ligne', meaning: 'resemble / look like', present: 'ligner', past: 'lignede', perfect: 'har lignet', imp: 'lign', group: 'ede' },
  { id: 303, inf: 'at lokke', meaning: 'lure / tempt', present: 'lokker', past: 'lokkede', perfect: 'har lokket', imp: 'lokk', group: 'ede' },
  { id: 304, inf: 'at love', meaning: 'promise', present: 'lover', past: 'lovede', perfect: 'har lovet', imp: 'lov', group: 'ede' },
  { id: 305, inf: 'at lyde', meaning: 'sound', present: 'lyder', past: 'lød', perfect: 'har lydt', imp: 'lyd', group: 'irregular' },
  { id: 306, inf: 'at lykkes', meaning: 'succeed', present: 'lykkes', past: 'lykkedes', perfect: 'er lykkedes', imp: 'lykkes', group: 'irregular' },
  { id: 307, inf: 'at lyse', meaning: 'shine', present: 'lyser', past: 'lyste', perfect: 'har lyst', imp: 'lys', group: 'te' },
  { id: 308, inf: 'at lytte', meaning: 'listen', present: 'lytter', past: 'lyttede', perfect: 'har lyttet', imp: 'lytt', group: 'ede' },
  { id: 309, inf: 'at løfte', meaning: 'lift / raise', present: 'løfter', past: 'løftede', perfect: 'har løftet', imp: 'løft', group: 'ede' },
  { id: 310, inf: 'at løse', meaning: 'solve', present: 'løser', past: 'løste', perfect: 'har løst', imp: 'løs', group: 'te' },
  { id: 311, inf: 'at låne', meaning: 'borrow / lend', present: 'låner', past: 'lånte', perfect: 'har lånt', imp: 'lån', group: 'te' },
  { id: 312, inf: 'at male', meaning: 'paint', present: 'maler', past: 'malede', perfect: 'har malet', imp: 'mal', group: 'ede' },
  { id: 313, inf: 'at mangle', meaning: 'lack / miss', present: 'mangler', past: 'manglede', perfect: 'har manglet', imp: 'mangl', group: 'ede' },
  { id: 314, inf: 'at meddele', meaning: 'inform / notify', present: 'meddeler', past: 'meddelte', perfect: 'har meddelt', imp: 'meddel', group: 'te' },
  { id: 315, inf: 'at medføre', meaning: 'entail / lead to', present: 'medfører', past: 'medførte', perfect: 'har medført', imp: 'medfør', group: 'te' },
  { id: 316, inf: 'at medvirke', meaning: 'contribute / participate', present: 'medvirker', past: 'medvirkede', perfect: 'har medvirket', imp: 'medvirk', group: 'ede' },
  { id: 317, inf: 'at melde', meaning: 'report / register', present: 'melder', past: 'meldte', perfect: 'har meldt', imp: 'meld', group: 'te' },
  { id: 318, inf: 'at minde', meaning: 'remind', present: 'minder', past: 'mindede', perfect: 'har mindet', imp: 'mind', group: 'ede' },
  { id: 319, inf: 'at miste', meaning: 'lose', present: 'mister', past: 'mistede', perfect: 'har mistet', imp: 'mist', group: 'ede' },
  { id: 320, inf: 'at modtage', meaning: 'receive', present: 'modtager', past: 'modtog', perfect: 'har modtaget', imp: 'modtag', group: 'irregular' },
  { id: 321, inf: 'at myrde', meaning: 'murder', present: 'myrder', past: 'myrdede', perfect: 'har myrdet', imp: 'myrd', group: 'ede' },
  { id: 322, inf: 'at mærke', meaning: 'notice / feel', present: 'mærker', past: 'mærkede', perfect: 'har mærket', imp: 'mærk', group: 'ede' },
  { id: 323, inf: 'at mødes', meaning: 'meet each other', present: 'mødes', past: 'mødtes', perfect: 'har mødtes', imp: 'mødes', group: 'irregular' },
  { id: 324, inf: 'at måle', meaning: 'measure', present: 'måler', past: 'målte', perfect: 'har målt', imp: 'mål', group: 'te' },
  { id: 325, inf: 'at nedlægge', meaning: 'shut down / abolish', present: 'nedlægger', past: 'nedlagde', perfect: 'har nedlagt', imp: 'nedlægg', group: 'irregular' },
  { id: 326, inf: 'at nedsætte', meaning: 'reduce / appoint', present: 'nedsætter', past: 'nedsatte', perfect: 'har nedsat', imp: 'nedsætt', group: 'irregular' },
  { id: 327, inf: 'at nikke', meaning: 'nod', present: 'nikker', past: 'nikkede', perfect: 'har nikket', imp: 'nikk', group: 'ede' },
  { id: 328, inf: 'at notere', meaning: 'note / record', present: 'noterer', past: 'noterede', perfect: 'har noteret', imp: 'noter', group: 'ede' },
  { id: 329, inf: 'at nyde', meaning: 'enjoy', present: 'nyder', past: 'nød', perfect: 'har nydt', imp: 'nyd', group: 'irregular' },
  { id: 330, inf: 'at nægte', meaning: 'deny / refuse', present: 'nægter', past: 'nægtede', perfect: 'har nægtet', imp: 'nægt', group: 'ede' },
  { id: 331, inf: 'at nærme sig', meaning: 'approach / get closer', present: 'nærmer sig', past: 'nærmede sig', perfect: 'har nærmet sig', imp: 'nærm sig', group: 'ede' },
  { id: 332, inf: 'at nøjes med', meaning: 'make do with / settle for', present: 'nøjes med', past: 'nøjedes med', perfect: 'har nøjedes', imp: 'nøjes med', group: 'irregular' },
  { id: 333, inf: 'at nå', meaning: 'reach / achieve', present: 'når', past: 'nåede', perfect: 'har nået', imp: 'nå', group: 'ede' },
  { id: 334, inf: 'at offentliggøre', meaning: 'publish / disclose', present: 'offentliggør', past: 'offentliggjorde', perfect: 'har offentlig-gjort', imp: 'offentliggør', group: 'irregular' },
  { id: 335, inf: 'at omfatte', meaning: 'include / cover', present: 'omfatter', past: 'omfattede', perfect: 'har omfattet', imp: 'omfatt', group: 'ede' },
  { id: 336, inf: 'at omgive', meaning: 'surround', present: 'omgiver', past: 'omgav', perfect: 'har omgivet', imp: 'omgiv', group: 'irregular' },
  { id: 337, inf: 'at opbygge', meaning: 'build up', present: 'opbygger', past: 'opbyggede', perfect: 'har opbygget', imp: 'opbygg', group: 'ede' },
  { id: 338, inf: 'at opdage', meaning: 'discover', present: 'opdager', past: 'opdagede', perfect: 'har opdaget', imp: 'opdag', group: 'ede' },
  { id: 339, inf: 'at operere', meaning: 'operate', present: 'opererer', past: 'opererede', perfect: 'har opereret', imp: 'operer', group: 'ede' },
  { id: 340, inf: 'at opfatte', meaning: 'perceive / understand', present: 'opfatter', past: 'opfattede', perfect: 'har opfattet', imp: 'opfatt', group: 'ede' },
  { id: 341, inf: 'at opfinde', meaning: 'invent', present: 'opfinder', past: 'opfandt', perfect: 'har opfundet', imp: 'opfind', group: 'irregular' },
  { id: 342, inf: 'at opfordre', meaning: 'encourage / urge', present: 'opfordrer', past: 'opfordrede', perfect: 'har opfordret', imp: 'opfordr', group: 'ede' },
  { id: 343, inf: 'at opfylde', meaning: 'fulfill / meet', present: 'opfylder', past: 'opfyldte', perfect: 'har opfyldt', imp: 'opfyld', group: 'te' },
  { id: 344, inf: 'at opføre', meaning: 'build / perform', present: 'opfører', past: 'opførte', perfect: 'har opført', imp: 'opfør', group: 'te' },
  { id: 345, inf: 'at opgive', meaning: 'give up', present: 'opgiver', past: 'opgav', perfect: 'har opgivet', imp: 'opgiv', group: 'irregular' },
  { id: 346, inf: 'at ophæve', meaning: 'repeal / lift', present: 'ophæver', past: 'ophævede', perfect: 'har ophævet', imp: 'ophæv', group: 'ede' },
  { id: 347, inf: 'at oplyse', meaning: 'inform / enlighten', present: 'oplyser', past: 'oplyste', perfect: 'har oplyst', imp: 'oplys', group: 'te' },
  { id: 348, inf: 'at opnå', meaning: 'achieve / attain', present: 'opnår', past: 'opnåede', perfect: 'har opnået', imp: 'opnå', group: 'ede' },
  { id: 349, inf: 'at oprette', meaning: 'create / establish', present: 'opretter', past: 'oprettede', perfect: 'har oprettet', imp: 'oprett', group: 'ede' },
  { id: 350, inf: 'at opstille', meaning: 'set up / propose', present: 'opstiller', past: 'opstillede', perfect: 'har opstillet', imp: 'opstill', group: 'ede' },
  { id: 351, inf: 'at opstå', meaning: 'arise / occur', present: 'opstår', past: 'opstod', perfect: 'er opstået', imp: 'opstå', group: 'irregular' },
  { id: 352, inf: 'at optage', meaning: 'record / absorb', present: 'optager', past: 'optog', perfect: 'har optaget', imp: 'optag', group: 'irregular' },
  { id: 353, inf: 'at optræde', meaning: 'perform / appear', present: 'optræder', past: 'optrådte', perfect: 'har optrådt', imp: 'optræd', group: 'irregular' },
  { id: 354, inf: 'at orientere', meaning: 'orient / inform', present: 'orienterer', past: 'orienterede', perfect: 'har orienteret', imp: 'orienter', group: 'ede' },
  { id: 355, inf: 'at overbevise', meaning: 'convince', present: 'overbeviser', past: 'overbeviste', perfect: 'har overbevist', imp: 'overbevis', group: 'te' },
  { id: 356, inf: 'at overføre', meaning: 'transfer', present: 'overfører', past: 'overførte', perfect: 'har overført', imp: 'overfør', group: 'te' },
  { id: 357, inf: 'at overholde', meaning: 'comply with', present: 'overholder', past: 'overholdt', perfect: 'har overholdt', imp: 'overhold', group: 'irregular' },
  { id: 358, inf: 'at overlade', meaning: 'leave to / entrust', present: 'overlader', past: 'overlod', perfect: 'har overladt', imp: 'overlad', group: 'irregular' },
  { id: 359, inf: 'at overleve', meaning: 'survive', present: 'overlever', past: 'overlevede', perfect: 'har overlevet', imp: 'overlev', group: 'ede' },
  { id: 360, inf: 'at overraske', meaning: 'surprise', present: 'overrasker', past: 'overraskede', perfect: 'har overrasket', imp: 'overrask', group: 'ede' },
  { id: 361, inf: 'at overtage', meaning: 'take over', present: 'overtager', past: 'overtog', perfect: 'har overtaget', imp: 'overtag', group: 'irregular' },
  { id: 362, inf: 'at overveje', meaning: 'consider', present: 'overvejer', past: 'overvejede', perfect: 'har overvejet', imp: 'overvej', group: 'ede' },
  { id: 363, inf: 'at pakke', meaning: 'pack', present: 'pakker', past: 'pakkede', perfect: 'har pakket', imp: 'pakk', group: 'ede' },
  { id: 364, inf: 'at pege', meaning: 'point', present: 'peger', past: 'pegede', perfect: 'har peget', imp: 'peg', group: 'ede' },
  { id: 365, inf: 'at placere', meaning: 'place', present: 'placerer', past: 'placerede', perfect: 'har placeret', imp: 'placer', group: 'ede' },
  { id: 366, inf: 'at planlægge', meaning: 'plan', present: 'planlægger', past: 'planlagde', perfect: 'har planlagt', imp: 'planlægg', group: 'irregular' },
  { id: 367, inf: 'at pleje', meaning: 'care for / tend', present: 'plejer', past: 'plejede', perfect: 'har plejet', imp: 'plej', group: 'ede' },
  { id: 368, inf: 'at presse', meaning: 'press / squeeze', present: 'presser', past: 'pressede', perfect: 'har presset', imp: 'press', group: 'ede' },
  { id: 369, inf: 'at producere', meaning: 'produce', present: 'producerer', past: 'producerede', perfect: 'har produceret', imp: 'producer', group: 'ede' },
  { id: 370, inf: 'at præge', meaning: 'shape / characterize', present: 'præger', past: 'prægede', perfect: 'har præget', imp: 'præg', group: 'ede' },
  { id: 371, inf: 'at præsentere', meaning: 'present', present: 'præsenterer', past: 'præsenterede', perfect: 'har præsenteret', imp: 'præsenter', group: 'ede' },
  { id: 372, inf: 'at pudse', meaning: 'polish / clean', present: 'pudser', past: 'pudsede', perfect: 'har pudset', imp: 'puds', group: 'ede' },
  { id: 373, inf: 'at påvirke', meaning: 'affect / influence', present: 'påvirker', past: 'påvirkede', perfect: 'har påvirket', imp: 'påvirk', group: 'ede' },
  { id: 374, inf: 'at ramme', meaning: 'hit', present: 'rammer', past: 'ramte', perfect: 'har ramt', imp: 'ramm', group: 'te' },
  { id: 375, inf: 'at reagere', meaning: 'react', present: 'reagerer', past: 'reagerede', perfect: 'har reageret', imp: 'reager', group: 'ede' },
  { id: 376, inf: 'at redde', meaning: 'rescue / save', present: 'redder', past: 'reddede', perfect: 'har reddet', imp: 'redd', group: 'ede' },
  { id: 377, inf: 'at reducere', meaning: 'reduce', present: 'reducerer', past: 'reducerede', perfect: 'har reduceret', imp: 'reducer', group: 'ede' },
  { id: 378, inf: 'at registrere', meaning: 'register / record', present: 'registrerer', past: 'registrerede', perfect: 'har registreret', imp: 'registrer', group: 'ede' },
  { id: 379, inf: 'at rense', meaning: 'clean / purify', present: 'renser', past: 'rensede', perfect: 'har renset', imp: 'rens', group: 'ede' },
  { id: 380, inf: 'at repræsentere', meaning: 'represent', present: 'repræsenterer', past: 'repræsenterede', perfect: 'har repræsen-teret', imp: 'repræsenter', group: 'ede' },
  { id: 381, inf: 'at respektere', meaning: 'respect', present: 'respekterer', past: 'respekterede', perfect: 'har respekteret', imp: 'respekter', group: 'ede' },
  { id: 382, inf: 'at rette', meaning: 'correct / direct', present: 'retter', past: 'rettede', perfect: 'har rettet', imp: 'rett', group: 'ede' },
  { id: 383, inf: 'at ride', meaning: 'ride', present: 'rider', past: 'red', perfect: 'har redet', imp: 'rid', group: 'irregular' },
  { id: 384, inf: 'at risikere', meaning: 'risk', present: 'risikerer', past: 'risikerede', perfect: 'har risikeret', imp: 'risiker', group: 'ede' },
  { id: 385, inf: 'at rive', meaning: 'tear / rip', present: 'river', past: 'rev', perfect: 'har revet', imp: 'riv', group: 'irregular' },
  { id: 386, inf: 'at rose', meaning: 'praise', present: 'roser', past: 'roste', perfect: 'har rost', imp: 'ros', group: 'te' },
  { id: 387, inf: 'at rulle', meaning: 'roll', present: 'ruller', past: 'rullede', perfect: 'har/er rullet', imp: 'rull', group: 'ede' },
  { id: 388, inf: 'at rumme', meaning: 'contain / accommodate', present: 'rummer', past: 'rummede', perfect: 'har rummet', imp: 'rumm', group: 'ede' },
  { id: 389, inf: 'at rydde', meaning: 'clear / tidy', present: 'rydder', past: 'ryddede', perfect: 'har ryddet', imp: 'rydd', group: 'ede' },
  { id: 390, inf: 'at ryge', meaning: 'smoke', present: 'ryger', past: 'røg', perfect: 'har røget', imp: 'ryg', group: 'irregular' },
  { id: 391, inf: 'at rykke', meaning: 'move / shift', present: 'rykker', past: 'rykkede', perfect: 'har rykket', imp: 'rykk', group: 'ede' },
  { id: 392, inf: 'at ryste', meaning: 'shake', present: 'ryster', past: 'rystede', perfect: 'har rystet', imp: 'ryst', group: 'ede' },
  { id: 393, inf: 'at række', meaning: 'reach / hand', present: 'rækker', past: 'rakte', perfect: 'har rakt', imp: 'rækk', group: 'irregular' },
  { id: 394, inf: 'at røre', meaning: 'touch / stir', present: 'rører', past: 'rørte', perfect: 'har rørt', imp: 'rør', group: 'te' },
  { id: 395, inf: 'at råbe', meaning: 'shout', present: 'råber', past: 'råbte', perfect: 'har råbt', imp: 'råb', group: 'te' },
  { id: 396, inf: 'at råde', meaning: 'advise', present: 'råder', past: 'rådede', perfect: 'har rådet', imp: 'råd', group: 'ede' },
  { id: 397, inf: 'at samle', meaning: 'collect / gather', present: 'samler', past: 'samlede', perfect: 'har samlet', imp: 'saml', group: 'ede' },
  { id: 398, inf: 'at sammenligne', meaning: 'compare', present: 'sammenligner', past: 'sammenlignede', perfect: 'har sammen-lignet', imp: 'sammenlign', group: 'ede' },
  { id: 399, inf: 'at satse', meaning: 'bet / invest', present: 'satser', past: 'satsede', perfect: 'har satset', imp: 'sats', group: 'ede' },
  { id: 400, inf: 'at savne', meaning: 'miss / long for', present: 'savner', past: 'savnede', perfect: 'har savnet', imp: 'savn', group: 'ede' },
  { id: 401, inf: 'at sejle', meaning: 'sail', present: 'sejler', past: 'sejlede', perfect: 'har sejlet', imp: 'sejl', group: 'ede' },
  { id: 402, inf: 'at servere', meaning: 'serve', present: 'serverer', past: 'serverede', perfect: 'har serveret', imp: 'server', group: 'ede' },
  { id: 403, inf: 'at ses', meaning: 'see each other / meet', present: 'ses', past: 'sås', perfect: 'har sets', imp: 'ses', group: 'irregular' },
  { id: 404, inf: 'at sikre', meaning: 'secure / ensure', present: 'sikrer', past: 'sikrede', perfect: 'har sikret', imp: 'sikr', group: 'ede' },
  { id: 405, inf: 'at skade', meaning: 'injure / harm', present: 'skader', past: 'skadede', perfect: 'har skadet', imp: 'skad', group: 'ede' },
  { id: 406, inf: 'at skaffe', meaning: 'obtain / get', present: 'skaffer', past: 'skaffede', perfect: 'har skaffet', imp: 'skaff', group: 'ede' },
  { id: 407, inf: 'at skifte', meaning: 'change / switch', present: 'skifter', past: 'skiftede', perfect: 'har skiftet', imp: 'skift', group: 'ede' },
  { id: 408, inf: 'at skinne', meaning: 'shine', present: 'skinner', past: 'skinnede', perfect: 'har skinnet', imp: 'skinn', group: 'ede' },
  { id: 409, inf: 'at skjule', meaning: 'hide / conceal', present: 'skjuler', past: 'skjulte', perfect: 'har skjult', imp: 'skjul', group: 'te' },
  { id: 410, inf: 'at skrige', meaning: 'scream / shout', present: 'skriger', past: 'skreg', perfect: 'har skreget', imp: 'skrig', group: 'irregular' },
  { id: 411, inf: 'at skræmme', meaning: 'scare / frighten', present: 'skræmmer', past: 'skræmte', perfect: 'har skræmt', imp: 'skræmm', group: 'te' },
  { id: 412, inf: 'at skubbe', meaning: 'push', present: 'skubber', past: 'skubbede', perfect: 'har skubbet', imp: 'skubb', group: 'ede' },
  { id: 413, inf: 'at skuffe', meaning: 'disappoint / deceive', present: 'skuffer', past: 'skuffede', perfect: 'har skuffet', imp: 'skuff', group: 'ede' },
  { id: 414, inf: 'at skyde', meaning: 'shoot', present: 'skyder', past: 'skød', perfect: 'har skudt', imp: 'skyd', group: 'irregular' },
  { id: 415, inf: 'at skyldes', meaning: 'be due to', present: 'skyldes', past: 'skyldtes', perfect: 'har skyldtes', imp: 'skyldes', group: 'irregular' },
  { id: 416, inf: 'at skære', meaning: 'cut', present: 'skærer', past: 'skar', perfect: 'har skåret', imp: 'skær', group: 'irregular' },
  { id: 417, inf: 'at slippe', meaning: 'let go / escape', present: 'slipper', past: 'slap', perfect: 'har/ersluppet', imp: 'slipp', group: 'irregular' },
  { id: 418, inf: 'at slukke', meaning: 'turn off', present: 'slukker', past: 'slukkede', perfect: 'er slukket', imp: 'slukk', group: 'ede' },
  { id: 419, inf: 'at slutte', meaning: 'end / close', present: 'slutter', past: 'sluttede', perfect: 'er sluttet', imp: 'slutt', group: 'ede' },
  { id: 420, inf: 'at slås', meaning: 'fight / struggle', present: 'slås', past: 'sloges', perfect: 'har sloges', imp: 'slås', group: 'irregular' },
  { id: 421, inf: 'at smage', meaning: 'taste', present: 'smager', past: 'smagte', perfect: 'har smagt', imp: 'smag', group: 'te' },
  { id: 422, inf: 'at smide', meaning: 'throw away / toss', present: 'smider', past: 'smed', perfect: 'har smidt', imp: 'smid', group: 'irregular' },
  { id: 423, inf: 'at smile', meaning: 'smile', present: 'smiler', past: 'smilede', perfect: 'har smilet', imp: 'smil', group: 'ede' },
  { id: 424, inf: 'at smitte', meaning: 'infect / spread', present: 'smitter', past: 'smittede', perfect: 'har smittet', imp: 'smitt', group: 'ede' },
  { id: 425, inf: 'at snakke', meaning: 'talk', present: 'snakker', past: 'snakkede', perfect: 'har snakket', imp: 'snakk', group: 'ede' },
  { id: 426, inf: 'at spare', meaning: 'save / spare', present: 'sparer', past: 'sparede', perfect: 'har sparet', imp: 'spar', group: 'ede' },
  { id: 427, inf: 'at spille', meaning: 'play', present: 'spiller', past: 'spillede', perfect: 'har spillet', imp: 'spill', group: 'ede' },
  { id: 428, inf: 'at sprede', meaning: 'spread', present: 'spreder', past: 'spredte', perfect: 'har spredt', imp: 'spred', group: 'te' },
  { id: 429, inf: 'at springe', meaning: 'jump / burst', present: 'springer', past: 'sprang', perfect: 'har/er sprunget', imp: 'spring', group: 'irregular' },
  { id: 430, inf: 'at stamme', meaning: 'stammer / originate', present: 'stammer', past: 'stammede', perfect: 'har stammet', imp: 'stamm', group: 'ede' },
  { id: 431, inf: 'at standse', meaning: 'stop', present: 'standser', past: 'standsede', perfect: 'har/er standset', imp: 'stands', group: 'ede' },
  { id: 432, inf: 'at stemme', meaning: 'vote / match', present: 'stemmer', past: 'stemte', perfect: 'har stemt', imp: 'stemm', group: 'te' },
  { id: 433, inf: 'at stege', meaning: 'fry / roast', present: 'steger', past: 'stegte', perfect: 'har stegt', imp: 'steg', group: 'te' },
  { id: 434, inf: 'at stige', meaning: 'rise / increase', present: 'stiger', past: 'steg', perfect: 'er steget', imp: 'stig', group: 'irregular' },
  { id: 435, inf: 'at stikke', meaning: 'stick / stab', present: 'stikker', past: 'stak', perfect: 'har stukket', imp: 'stikk', group: 'irregular' },
  { id: 436, inf: 'at stikke af', meaning: 'run away / escape', present: 'stikker af', past: 'stak af', perfect: 'er stukket af', imp: 'stikk af', group: 'irregular' },
  { id: 437, inf: 'at stjæle', meaning: 'steal', present: 'stjæler', past: 'stjal', perfect: 'har stjålet', imp: 'stjæl', group: 'irregular' },
  { id: 438, inf: 'at stole på', meaning: 'trust / rely on', present: 'stoler på', past: 'stolede på', perfect: 'har stolet på', imp: 'stol på', group: 'ede' },
  { id: 439, inf: 'at stoppe', meaning: 'stop', present: 'stopper', past: 'stoppede', perfect: 'har/er stoppet', imp: 'stopp', group: 'ede' },
  { id: 440, inf: 'at straffe', meaning: 'punish', present: 'straffer', past: 'straffede', perfect: 'har straffet', imp: 'straff', group: 'ede' },
  { id: 441, inf: 'at stramme', meaning: 'tighten', present: 'strammer', past: 'strammede', perfect: 'har strammet', imp: 'stramm', group: 'ede' },
  { id: 442, inf: 'at strække', meaning: 'stretch', present: 'strækker', past: 'strakte', perfect: 'har strakt', imp: 'strækk', group: 'te' },
  { id: 443, inf: 'at studere', meaning: 'study', present: 'studerer', past: 'studerede', perfect: 'har studeret', imp: 'studer', group: 'ede' },
  { id: 444, inf: 'at styre', meaning: 'control / steer', present: 'styrer', past: 'styrede', perfect: 'har styret', imp: 'styr', group: 'ede' },
  { id: 445, inf: 'at styrke', meaning: 'strengthen', present: 'styrker', past: 'styrkede', perfect: 'har styrket', imp: 'styrk', group: 'ede' },
  { id: 446, inf: 'at støde', meaning: 'bump / thrust', present: 'støder', past: 'stødte', perfect: 'har stødt', imp: 'stød', group: 'te' },
  { id: 447, inf: 'at støde på', meaning: 'encounter / come across', present: 'støder på', past: 'stødte på', perfect: 'er stødt på', imp: 'stød på', group: 'te' },
  { id: 448, inf: 'at støtte', meaning: 'support', present: 'støtter', past: 'støttede', perfect: 'har støttet', imp: 'støtt', group: 'ede' },
  { id: 449, inf: 'at stå op', meaning: 'get up / stand up', present: 'står op', past: 'stod op', perfect: 'er stået op', imp: 'stå op', group: 'irregular' },
  { id: 450, inf: 'at svigte', meaning: 'fail / let down', present: 'svigter', past: 'svigtede', perfect: 'har sviget', imp: 'svigt', group: 'ede' },
  { id: 451, inf: 'at svinge', meaning: 'swing', present: 'svinger', past: 'svingede', perfect: 'har svinget', imp: 'sving', group: 'ede' },
  { id: 452, inf: 'at sy', meaning: 'sew', present: 'syr', past: 'syede', perfect: 'har syet', imp: 'sy', group: 'ede' },
  { id: 453, inf: 'at synge', meaning: 'sing', present: 'synger', past: 'sang', perfect: 'har sunget', imp: 'syng', group: 'irregular' },
  { id: 454, inf: 'at synke', meaning: 'sink', present: 'synker', past: 'sank', perfect: 'er sunket', imp: 'synk', group: 'irregular' },
  { id: 455, inf: 'at sænke', meaning: 'lower / reduce', present: 'sænker', past: 'sænkede', perfect: 'har sænket', imp: 'sænk', group: 'ede' },
  { id: 456, inf: 'at søge', meaning: 'seek / apply', present: 'søger', past: 'søgte', perfect: 'har søgt', imp: 'søg', group: 'te' },
  { id: 457, inf: 'at sørge for', meaning: 'make sure / take care of', present: 'sørger for', past: 'sørgede for', perfect: 'har sørget for', imp: 'sørg for', group: 'ede' },
  { id: 458, inf: 'at tabe', meaning: 'lose', present: 'taber', past: 'tabte', perfect: 'har tabt', imp: 'tab', group: 'te' },
  { id: 459, inf: 'at tage hjem', meaning: 'go home / take home', present: 'tager hjem', past: 'tog hjem', perfect: 'er taget hjem', imp: 'tag hjem', group: 'irregular' },
  { id: 460, inf: 'at takke', meaning: 'thank', present: 'takker', past: 'takkede', perfect: 'har takket', imp: 'takk', group: 'ede' },
  { id: 461, inf: 'at tegne', meaning: 'draw', present: 'tegner', past: 'tegnede', perfect: 'har tegnet', imp: 'tegn', group: 'ede' },
  { id: 462, inf: 'at tilbringe', meaning: 'spend', present: 'tilbringer', past: 'tilbragte', perfect: 'har tilbragt', imp: 'tilbring', group: 'irregular' },
  { id: 463, inf: 'at tilbyde', meaning: 'offer', present: 'tilbyder', past: 'tilbød', perfect: 'har tilbudt', imp: 'tilbyd', group: 'irregular' },
  { id: 464, inf: 'at tilføje', meaning: 'add', present: 'tilføjer', past: 'tilføjede', perfect: 'har tilføjet', imp: 'tilføj', group: 'ede' },
  { id: 465, inf: 'at tilhøre', meaning: 'belong to', present: 'tilhører', past: 'tilhørte', perfect: 'har tilhørt', imp: 'tilhør', group: 'te' },
  { id: 466, inf: 'at tillade', meaning: 'allow', present: 'tillader', past: 'tillod', perfect: 'har tilladt', imp: 'tillad', group: 'irregular' },
  { id: 467, inf: 'at tjene', meaning: 'earn / serve', present: 'tjener', past: 'tjente', perfect: 'har tjent', imp: 'tjen', group: 'te' },
  { id: 468, inf: 'at true', meaning: 'threaten', present: 'truer', past: 'truede', perfect: 'har truet', imp: 'tru', group: 'ede' },
  { id: 469, inf: 'at trykke', meaning: 'press / print', present: 'trykker', past: 'trykkede', perfect: 'har trykket', imp: 'trykk', group: 'ede' },
  { id: 470, inf: 'at træde', meaning: 'step / tread', present: 'træder', past: 'trådte', perfect: 'har trådt', imp: 'træd', group: 'irregular' },
  { id: 471, inf: 'at trække', meaning: 'pull / draw', present: 'trækker', past: 'trak', perfect: 'har trukket', imp: 'trækk', group: 'irregular' },
  { id: 472, inf: 'at trænge', meaning: 'force / press', present: 'trænger', past: 'trængte', perfect: 'har trængt', imp: 'træng', group: 'te' },
  { id: 473, inf: 'at trænge ind', meaning: 'intrude / penetrate', present: 'trænger ind', past: 'trængte ind', perfect: 'er trængt ind', imp: 'træng ind', group: 'te' },
  { id: 474, inf: 'at turde', meaning: 'dare', present: 'tør', past: 'turde', perfect: 'har turdet', imp: 'turd', group: 'irregular' },
  { id: 475, inf: 'at tvinge', meaning: 'force / compel', present: 'tvinger', past: 'tvang', perfect: 'har tvunget', imp: 'tving', group: 'irregular' },
  { id: 476, inf: 'at tyde', meaning: 'interpret / indicate', present: 'tyder', past: 'tydede', perfect: 'har tydet', imp: 'tyd', group: 'ede' },
  { id: 477, inf: 'at tælle', meaning: 'count', present: 'tæller', past: 'talte', perfect: 'har talt', imp: 'tæll', group: 'irregular' },
  { id: 478, inf: 'at tænde', meaning: 'turn on / light', present: 'tænder', past: 'tændte', perfect: 'har tændt', imp: 'tænd', group: 'te' },
  { id: 479, inf: 'at tømme', meaning: 'empty', present: 'tømmer', past: 'tømte', perfect: 'har tømt', imp: 'tømm', group: 'te' },
  { id: 480, inf: 'at tørre', meaning: 'dry', present: 'tørrer', past: 'tørrede', perfect: 'har tørret', imp: 'tørr', group: 'ede' },
  { id: 481, inf: 'at tåle', meaning: 'tolerate / endure', present: 'tåler', past: 'tålte', perfect: 'har tålt', imp: 'tål', group: 'te' },
  { id: 482, inf: 'at udarbejde', meaning: 'prepare / draft', present: 'udarbejder', past: 'udarbejdede', perfect: 'har udarbejdet', imp: 'udarbejd', group: 'ede' },
  { id: 483, inf: 'at udbrede', meaning: 'spread', present: 'udbreder', past: 'udbredte', perfect: 'har udbredt', imp: 'udbred', group: 'te' },
  { id: 484, inf: 'at uddanne', meaning: 'educate / train', present: 'uddanner', past: 'uddannede', perfect: 'har uddannet', imp: 'uddann', group: 'ede' },
  { id: 485, inf: 'at udelukke', meaning: 'exclude', present: 'udelukker', past: 'udelukkede', perfect: 'har udelukket', imp: 'udelukk', group: 'ede' },
  { id: 486, inf: 'at udføre', meaning: 'carry out / perform', present: 'udfører', past: 'udførte', perfect: 'har udført', imp: 'udfør', group: 'te' },
  { id: 487, inf: 'at udgive', meaning: 'publish / release', present: 'udgiver', past: 'udgav', perfect: 'har udgivet', imp: 'udgiv', group: 'irregular' },
  { id: 488, inf: 'at udgøre', meaning: 'constitute / make up', present: 'udgør', past: 'udgjorde', perfect: 'har udgjort', imp: 'udgør', group: 'irregular' },
  { id: 489, inf: 'at udkomme', meaning: 'come out / be published', present: 'udkommer', past: 'udkom', perfect: 'er udkommet', imp: 'udkomm', group: 'irregular' },
  { id: 490, inf: 'at udlevere', meaning: 'hand over / disclose', present: 'udleverer', past: 'udleverede', perfect: 'har udleveret', imp: 'udlever', group: 'ede' },
  { id: 491, inf: 'at udløse', meaning: 'trigger', present: 'udløser', past: 'udløste', perfect: 'har udløst', imp: 'udløs', group: 'te' },
  { id: 492, inf: 'at udnytte', meaning: 'exploit / use', present: 'udnytter', past: 'udnyttede', perfect: 'har udnyttet', imp: 'udnytt', group: 'ede' },
  { id: 493, inf: 'at udstyre', meaning: 'equip', present: 'udstyrer', past: 'udstyrede', perfect: 'har udstyret', imp: 'udstyr', group: 'ede' },
  { id: 494, inf: 'at udsætte', meaning: 'postpone / expose', present: 'udsætter', past: 'udsatte', perfect: 'har udsat', imp: 'udsætt', group: 'irregular' },
  { id: 495, inf: 'at udtale', meaning: 'pronounce / express', present: 'udtaler', past: 'udtalte', perfect: 'har udtalt', imp: 'udtal', group: 'te' },
  { id: 496, inf: 'at udtrykke', meaning: 'express', present: 'udtrykker', past: 'udtrykte', perfect: 'har udtrykt', imp: 'udtrykk', group: 'te' },
  { id: 497, inf: 'at udvide', meaning: 'expand', present: 'udvider', past: 'uvidede', perfect: 'har udvidet', imp: 'udvid', group: 'ede' },
  { id: 498, inf: 'at underholde', meaning: 'entertain', present: 'underholder', past: 'underholdt', perfect: 'har underholdt', imp: 'underhold', group: 'irregular' },
  { id: 499, inf: 'at understrege', meaning: 'emphasize / underline', present: 'under-streger', past: 'understregede', perfect: 'har under-streget', imp: 'understreg', group: 'ede' },
  { id: 500, inf: 'at undersøge', meaning: 'investigate / examine', present: 'undersøger', past: 'undersøgte', perfect: 'har undersøgt', imp: 'undersøg', group: 'te' },
  { id: 501, inf: 'at undgå', meaning: 'avoid', present: 'undgår', past: 'undgik', perfect: 'har undgået', imp: 'undgå', group: 'irregular' },
  { id: 502, inf: 'at undre sig', meaning: 'wonder / be surprised', present: 'undrer sig', past: 'undrede sig', perfect: 'har undret sig', imp: 'undr sig', group: 'ede' },
  { id: 503, inf: 'at vaccinere', meaning: 'vaccinate', present: 'vaccinerer', past: 'vaccinerede', perfect: 'har vaccineret', imp: 'vacciner', group: 'ede' },
  { id: 504, inf: 'at vare', meaning: 'last', present: 'varer', past: 'varede', perfect: 'har varet', imp: 'var', group: 'ede' },
  { id: 505, inf: 'at variere', meaning: 'vary', present: 'varierer', past: 'varierede', perfect: 'har varieret', imp: 'varier', group: 'ede' },
  { id: 506, inf: 'at vaske', meaning: 'wash', present: 'vasker', past: 'vaskede', perfect: 'har vasket', imp: 'vask', group: 'ede' },
  { id: 507, inf: 'at vedtage', meaning: 'adopt / pass', present: 'vedtager', past: 'vedtog', perfect: 'har vedtaget', imp: 'vedtag', group: 'irregular' },
  { id: 508, inf: 'at veje', meaning: 'weigh', present: 'vejer', past: 'vejede', perfect: 'har vejet', imp: 'vej', group: 'ede' },
  { id: 509, inf: 'at vokse', meaning: 'grow', present: 'vokser', past: 'voksede', perfect: 'er vokset', imp: 'voks', group: 'ede' },
  { id: 510, inf: 'at vurdere', meaning: 'assess / evaluate', present: 'vurderer', past: 'vurderede', perfect: 'har vurderet', imp: 'vurder', group: 'ede' },
  { id: 511, inf: 'at vække', meaning: 'wake', present: 'vækker', past: 'vækkede', perfect: 'har vækket', imp: 'vækk', group: 'ede' },
  { id: 512, inf: 'at vælte', meaning: 'topple / tip over', present: 'vælter', past: 'væltede', perfect: 'har væltet', imp: 'vælt', group: 'ede' },
  { id: 513, inf: 'at vågne', meaning: 'wake up', present: 'vågner', past: 'vågnede', perfect: 'er vågnet', imp: 'vågn', group: 'ede' },
  { id: 514, inf: 'at yde', meaning: 'provide / perform', present: 'yder', past: 'ydede', perfect: 'har ydet', imp: 'yd', group: 'ede' },
  { id: 515, inf: 'at ødelægge', meaning: 'destroy', present: 'ødelægger', past: 'ødelagde', perfect: 'har ødelagt', imp: 'ødelægg', group: 'irregular' },
  { id: 516, inf: 'at øge', meaning: 'increase', present: 'øger', past: 'øgede', perfect: 'har øget', imp: 'øg', group: 'ede' }
];


// Groups of visually similar verbs (for English→Danish exercise distractors)
// Each array groups verbs whose Danish infinitives look alike
const WRITING_CLUSTERS = [

  ['at lave', 'at leve', 'at lade', 'at løbe', 'at lære'],
  ['at lægge', 'at ligge', 'at lukke', 'at læse'],
  ['at se', 'at sige', 'at sidde', 'at synes', 'at ske'],
  ['at sætte', 'at stille', 'at stå', 'at starte', 'at slå'],
  ['at svare', 'at sove', 'at spise', 'at sende', 'at spørge'],
  ['at sælge', 'at skrive', 'at skabe', 'at ske'],
  ['at vise', 'at vide', 'at virke', 'at vente', 'at vende'],
  ['at vinde', 'at vælge', 'at ville', 'at virke'],
  ['at gå', 'at gøre', 'at give', 'at få', 'at glemme'],
  ['at komme', 'at kalde', 'at kende', 'at kræve', 'at køre', 'at købe'],
  ['at finde', 'at falde', 'at følge', 'at føre', 'at føle', 'at flytte'],
  ['at fortælle', 'at forklare', 'at forsøge', 'at forstå', 'at fortsætte'],
  ['at begynde', 'at betale', 'at betyde', 'at bestemme', 'at besøge', 'at behøve'],
  ['at blive', 'at burde', 'at bo', 'at bruge', 'at bringe'],
  ['at handle', 'at holde', 'at høre', 'at hente', 'at huske', 'at hjælpe', 'at hedde'],
  ['at tage', 'at tale', 'at tænke', 'at træffe', 'at tro'],
  ['at mene', 'at møde', 'at måtte'],
  ['at ringe', 'at rejse', 'at regne'],
  ['at arbejde', 'at åbne', 'at ønske', 'at ændre', 'at opleve'],
  ['at elske', 'at ønske', 'at ændre', 'at åbne'],
  ['at prøve', 'at passe', 'at ringe', 'at rejse'],
  ['at udvikle', 'at ændre', 'at åbne', 'at arbejde'],
  ['at drikke', 'at sidde', 'at skrive', 'at sige'],
  ['at have', 'at handle', 'at hente', 'at huske', 'at holde'],
  ['at tro', 'at tage', 'at tale', 'at tænke'],
  ['at følge', 'at føle', 'at føre', 'at finde', 'at falde'],
  ['at spørge', 'at spise', 'at sende', 'at svare'],
  ['at afbryde', 'at afgive', 'at afgøre', 'at aflevere', 'at aflyse', 'at afløse', 'at afskaffe'],
  ['at anbefale', 'at anbringe', 'at ane', 'at anerkende', 'at angive', 'at angå', 'at anholde'],
  ['at ankomme', 'at anmelde', 'at anse', 'at ansætte', 'at anvende'],
  ['at bede', 'at befinde', 'at begrave', 'at begrænse', 'at begå', 'at behandle', 'at beholde'],
  ['at beklage', 'at bekræfte', 'at bemærke', 'at benytte', 'at beskrive', 'at beskytte', 'at beslutte'],
  ['at bestille', 'at bestå', 'at besætte', 'at bevare', 'at bevise', 'at bevæge sig'],
  ['at forbedre', 'at forberede', 'at forbinde', 'at forblive', 'at fordele', 'at foregå', 'at forekomme'],
  ['at forelske sig', 'at forene', 'at foreslå', 'at forestille sig', 'at foretage sig', 'at foretrække', 'at forhandle'],
  ['at forhindre', 'at forholde sig', 'at forlade', 'at forlange', 'at formulere', 'at formå', 'at forsinke'],
  ['at forsvare', 'at forsvinde', 'at fortjene', 'at forudsætte', 'at forvandle', 'at forvente'],
  ['at fremgå', 'at fremhæve', 'at fremlægge', 'at fremstille', 'at fremsætte'],
  ['at genere', 'at gennemføre', 'at gennemgå', 'at gentage'],
  ['at inddrage', 'at indebære', 'at indeholde', 'at indføre', 'at indgå', 'at indlede', 'at indrette'],
  ['at indrømme', 'at indstille', 'at indtage'],
  ['at meddele', 'at medføre', 'at medvirke'],
  ['at opbygge', 'at opdage', 'at operere', 'at opfatte', 'at opfinde', 'at opfordre', 'at opfylde'],
  ['at opføre', 'at opgive', 'at ophæve', 'at oplyse', 'at opnå', 'at oprette', 'at opstille'],
  ['at opstå', 'at optage', 'at optræde'],
  ['at overbevise', 'at overføre', 'at overholde', 'at overlade', 'at overleve', 'at overraske', 'at overtage'],
  ['at tilføje', 'at tilhøre', 'at tillade'],
  ['at udarbejde', 'at udbrede', 'at uddanne', 'at udelukke', 'at udføre', 'at udgive', 'at udgøre'],
  ['at udkomme', 'at udlevere', 'at udløse', 'at udnytte', 'at udstyre', 'at udsætte', 'at udtale'],
  ['at underholde', 'at understrege', 'at undersøge'],
  ['at bide', 'at bidrage', 'at binde'],
  ['at drage', 'at dreje', 'at drive', 'at dræbe', 'at drøfte', 'at drømme'],
  ['at fange', 'at fastholde', 'at fastslå', 'at fastsætte', 'at fatte'],
  ['at gribe', 'at grine', 'at græde'],
  ['at henvende sig', 'at henvise', 'at herske'],
  ['at hælde', 'at hænge (tr)', 'at hænge (intr)', 'at hævde', 'at hæve'],
  ['at installere', 'at inspirere', 'at interessere', 'at investere', 'at invitere'],
  ['at klare', 'at klippe', 'at klæde'],
  ['at koge', 'at kombinere', 'at kommentere', 'at koncentrere sig', 'at konstatere', 'at kontakte', 'at kontrollere'],
  ['at le', 'at lede', 'at lege', 'at leje', 'at lette', 'at levere'],
  ['at lyde', 'at lykkes', 'at lyse', 'at lytte'],
  ['at placere', 'at planlægge', 'at pleje'],
  ['at presse', 'at producere', 'at præge', 'at præsentere'],
  ['at reagere', 'at redde', 'at reducere', 'at registrere', 'at rense', 'at repræsentere', 'at respektere'],
  ['at ride', 'at risikere', 'at rive'],
  ['at rydde', 'at ryge', 'at rykke', 'at ryste'],
  ['at satse', 'at savne', 'at samle', 'at sammenligne'],
  ['at sejle', 'at servere', 'at ses'],
  ['at skade', 'at skaffe', 'at skifte', 'at skinne', 'at skjule', 'at skrige', 'at skræmme'],
  ['at skubbe', 'at skuffe', 'at skyde', 'at skyldes', 'at skære'],
  ['at slippe', 'at slukke', 'at slutte', 'at slås'],
  ['at smage', 'at smide', 'at smile', 'at smitte'],
  ['at spare', 'at spille', 'at sprede', 'at springe'],
  ['at stamme', 'at standse', 'at stemme', 'at stege', 'at stige', 'at stikke', 'at stikke af'],
  ['at stjæle', 'at stole på', 'at stoppe', 'at straffe', 'at stramme', 'at strække', 'at studere'],
  ['at styre', 'at styrke', 'at støde', 'at støde på', 'at støtte', 'at stå op'],
  ['at sy', 'at synge', 'at synke'],
  ['at tabe', 'at tage hjem', 'at takke'],
  ['at true', 'at trykke', 'at træde', 'at trække', 'at trænge', 'at trænge ind'],
  ['at vaccinere', 'at vare', 'at variere', 'at vaske'],
];

// Groups of semantically similar verbs (for Danish→English exercise distractors)
// Each array groups verbs whose English meanings are close
const MEANING_CLUSTERS = [

  // Think / believe / mean / seem
  ['at mene', 'at tro', 'at synes', 'at tænke'],
  // Want / wish / need / should / must / ought
  ['at ville', 'at ønske', 'at behøve', 'at burde', 'at skulle', 'at måtte'],
  // Say / tell / explain / answer / speak / ask
  ['at sige', 'at fortælle', 'at forklare', 'at svare', 'at tale', 'at spørge'],
  // Go / travel / move / drive / run / come / follow
  ['at gå', 'at rejse', 'at køre', 'at løbe', 'at flytte', 'at komme', 'at følge'],
  // Get / receive / bring / fetch / send
  ['at få', 'at hente', 'at bringe', 'at sende'],
  // See / show / find
  ['at se', 'at vise', 'at finde'],
  // Make / do / create / develop / work
  ['at gøre', 'at lave', 'at skabe', 'at arbejde', 'at udvikle'],
  // Know / understand / recognize
  ['at vide', 'at kende', 'at forstå'],
  // Put / place / lay / stand / sit / lie
  ['at stille', 'at lægge', 'at sætte', 'at ligge', 'at sidde', 'at stå'],
  // Live / reside / be / remain / become
  ['at leve', 'at bo', 'at være', 'at blive'],
  // Try / attempt / test
  ['at prøve', 'at forsøge'],
  // Begin / continue / start / happen
  ['at begynde', 'at fortsætte', 'at starte', 'at ske'],
  // Meet / visit / encounter
  ['at møde', 'at besøge', 'at træffe'],
  // Learn / teach / read / hear / understand
  ['at lære', 'at læse', 'at høre', 'at forstå'],
  // Pay / buy / sell / choose
  ['at betale', 'at købe', 'at sælge', 'at vælge'],
  // Love / feel / experience / wish
  ['at elske', 'at føle', 'at opleve', 'at ønske'],
  // Remember / forget / wait
  ['at huske', 'at glemme', 'at vente'],
  // Open / close
  ['at åbne', 'at lukke'],
  // Win / beat / hit / fall
  ['at vinde', 'at slå', 'at falde'],
  // Help / lead / follow / carry
  ['at hjælpe', 'at følge', 'at føre', 'at bringe'],
  // Change / develop / determine / require
  ['at ændre', 'at udvikle', 'at bestemme', 'at kræve'],
  // Work / seem / mean / signify
  ['at virke', 'at betyde', 'at synes', 'at mene'],
  // Eat / drink / sleep
  ['at spise', 'at drikke', 'at sove'],
  // Call / ring / name / be called
  ['at ringe', 'at kalde', 'at hedde'],
  // Use / take / bring / need
  ['at bruge', 'at tage', 'at bringe', 'at behøve'],
  // Fit / take care / act / handle
  ['at passe', 'at handle', 'at bestemme'],
  // Write / read / tell / explain
  ['at skrive', 'at læse', 'at fortælle', 'at forklare'],
  // Take / get / choose / give
  ['at tage', 'at få', 'at vælge', 'at give'],
  // Hold / keep / stand / sit
  ['at holde', 'at stå', 'at sidde', 'at ligge'],
  // Fall / run / go / walk
  ['at falde', 'at løbe', 'at gå'],
  // Give / let / allow
  ['at give', 'at lade', 'at tillade'],
  // Calculate / expect / count
  ['at regne', 'at betale', 'at kræve'],
  // Speak / call / ask / answer
  ['at tale', 'at kalde', 'at spørge', 'at svare'],
  // Turn / return / come / go
  ['at vende', 'at komme', 'at rejse'],
  // Create / make / develop / build
  ['at skabe', 'at lave', 'at udvikle'],
  // Ask / demand / require / need
  ['at spørge', 'at kræve', 'at bestemme', 'at behøve'],
  // Drive / travel / buy / run
  ['at køre', 'at rejse', 'at løbe'],
  // Use / need / have / get
  ['at bruge', 'at behøve', 'at have', 'at få'],
  // Send / bring / receive / get
  ['at sende', 'at bringe', 'at hente', 'at få'],
  // Hit / beat / win / fall
  ['at slå', 'at vinde', 'at falde'],

['at fastholde', 'at fastslå', 'at fastsætte', 'at gennemføre', 'at godkende', 'at kontakte', 'at planlægge'],
  ['at begrave', 'at begrænse', 'at erstatte', 'at forbedre', 'at forberede', 'at forbinde', 'at forblive'],
  ['at nedsætte', 'at reducere', 'at søge', 'at undersøge', 'at øge'],
  ['at ane', 'at anerkende', 'at bemærke', 'at beslutte', 'at bestille', 'at bestå', 'at erkende'],
  ['at forsinke', 'at forsvare', 'at forsvinde', 'at forvandle', 'at forvente', 'at kontrollere', 'at opfatte'],
  ['at registrere', 'at udvide', 'at vurdere'],
  ['at advare', 'at anbefale', 'at anmelde', 'at diskutere', 'at formulere', 'at formå', 'at fortjene'],
  ['at fremgå', 'at fremhæve', 'at fremlægge', 'at fremstille', 'at fremsætte', 'at kommentere', 'at konstatere'],
  ['at meddele', 'at melde', 'at oplyse', 'at orientere', 'at præsentere', 'at repræsentere', 'at snakke'],
  ['at arrangere', 'at bygge', 'at danne', 'at installere', 'at opbygge', 'at opstille', 'at opstå'],
  ['at afbryde', 'at aflyse', 'at afskaffe', 'at afvise', 'at beskrive', 'at bryde', 'at dræbe'],
  ['at fjerne', 'at myrde', 'at nedlægge', 'at rive', 'at skade', 'at ødelægge'],
  ['at beklage', 'at drømme', 'at foregå', 'at forekomme', 'at forelske sig', 'at forene', 'at foreslå'],
  ['at forestille sig', 'at foretage sig', 'at foretrække', 'at frygte', 'at genere', 'at glæde sig', 'at hade'],
  ['at håbe', 'at indrømme', 'at irritere', 'at nyde', 'at overbevise', 'at overføre', 'at overholde'],
  ['at overlade', 'at overleve', 'at overraske', 'at overtage', 'at overveje', 'at savne', 'at skræmme'],
  ['at angå', 'at begå', 'at bidrage', 'at brede sig', 'at drage', 'at drive', 'at flygte'],
  ['at flyve', 'at gennemgå', 'at glide', 'at hoppe', 'at inddrage', 'at indgå', 'at ride'],
  ['at rulle', 'at sejle', 'at sprede', 'at springe', 'at stige', 'at svinge', 'at udbrede'],
  ['at afgive', 'at aflevere', 'at anbringe', 'at angive', 'at beholde', 'at deltage', 'at gemme'],
  ['at gentage', 'at indtage', 'at levere', 'at modtage', 'at omgive', 'at opgive', 'at optage'],
  ['at pakke', 'at samle', 'at tage hjem', 'at tilbringe', 'at udgive', 'at udlevere', 'at vedtage'],
  ['at gifte sig', 'at hilse', 'at invitere', 'at mødes', 'at støtte'],
['at fastholde', 'at fastslå', 'at fastsætte', 'at gennemføre', 'at godkende', 'at kontakte', 'at planlægge'],
  ['at begrave', 'at begrænse', 'at erstatte', 'at forbedre', 'at forberede', 'at forbinde', 'at forblive'],
  ['at nedsætte', 'at reducere', 'at søge', 'at undersøge', 'at øge'],
  ['at ane', 'at anerkende', 'at bemærke', 'at beslutte', 'at bestille', 'at bestå', 'at erkende'],
  ['at forsinke', 'at forsvare', 'at forsvinde', 'at forvandle', 'at forvente', 'at kontrollere', 'at opfatte'],
  ['at registrere', 'at udvide', 'at vurdere'],
  ['at advare', 'at anbefale', 'at anmelde', 'at diskutere', 'at formulere', 'at formå', 'at fortjene'],
  ['at fremgå', 'at fremhæve', 'at fremlægge', 'at fremstille', 'at fremsætte', 'at kommentere', 'at konstatere'],
  ['at meddele', 'at melde', 'at oplyse', 'at orientere', 'at præsentere', 'at repræsentere', 'at snakke'],
  ['at arrangere', 'at bygge', 'at danne', 'at installere', 'at opbygge', 'at opstille', 'at opstå'],
  ['at afbryde', 'at aflyse', 'at afskaffe', 'at afvise', 'at beskrive', 'at bryde', 'at dræbe'],
  ['at fjerne', 'at myrde', 'at nedlægge', 'at rive', 'at skade', 'at ødelægge'],
  ['at beklage', 'at drømme', 'at foregå', 'at forekomme', 'at forelske sig', 'at forene', 'at foreslå'],
  ['at forestille sig', 'at foretage sig', 'at foretrække', 'at frygte', 'at genere', 'at glæde sig', 'at hade'],
  ['at håbe', 'at indrømme', 'at irritere', 'at nyde', 'at overbevise', 'at overføre', 'at overholde'],
  ['at overlade', 'at overleve', 'at overraske', 'at overtage', 'at overveje', 'at savne', 'at skræmme'],
  ['at angå', 'at begå', 'at bidrage', 'at brede sig', 'at drage', 'at drive', 'at flygte'],
  ['at flyve', 'at gennemgå', 'at glide', 'at hoppe', 'at inddrage', 'at indgå', 'at ride'],
  ['at rulle', 'at sejle', 'at sprede', 'at springe', 'at stige', 'at svinge', 'at udbrede'],
  ['at afgive', 'at aflevere', 'at anbringe', 'at angive', 'at beholde', 'at deltage', 'at gemme'],
  ['at gentage', 'at indtage', 'at levere', 'at modtage', 'at omgive', 'at opgive', 'at optage'],
  ['at pakke', 'at samle', 'at tage hjem', 'at tilbringe', 'at udgive', 'at udlevere', 'at vedtage'],
  ['at gifte sig', 'at hilse', 'at invitere', 'at mødes', 'at støtte'],
];
